### ISSUE TITLE
新功能建议(4个)

### ISSUE THREAD

**Issue by klpbbs** [lsky-org/lsky-pro#100]
1、添加一个设置，可以控制是否为点击自动复制
![image](https://cc.klpbbs.com/img/2020/03/19/f85c1820cae5d.png)
就是直接点这里的链接就可以复制
好处：可以方便手机的用户
2、添加一个图片预览功能
![image](https://cc.klpbbs.com/img/2020/03/19/9f6c8e700905b.png)
当鼠标滑动到上方链接时自动会弹出一个缩略图的悬浮窗口（不过这个可能对手机有点不友好）
3、建议在登录界面添加记住账号或自动登录选项
4、注册邮箱验证，或者邮箱接收验证码，顺便加个禁止注册指定邮箱注册的功能

QWQ是不是有点多了。。。

**Comment by wisp-x** [comment]
![3c6d55fbb2fb4316578fbb3129a4462308f7d3ed](https://user-images.githubusercontent.com/22728201/77081013-fc2ef180-6a34-11ea-8644-38005bde535c.jpg)
