### ISSUE TITLE
希望能用上Onedrive+反向代理sharepoint域名选项

### ISSUE THREAD

**Issue by imzrme** [lsky-org/lsky-pro#144]
如题

**Comment by wisp-x** [comment]
要求过高

**Comment by D-Myself** [comment]
> 要求过高

添加反向代理选项其实是在获取链接后更改域名为反代域名，不是很难的

**Comment by renbaoshuo** [comment]
> > 要求过高
> 
> 添加反向代理选项其实是在获取链接后更改域名为反代域名，不是很难的

**既然不难自己做也不是不行啊.jpg**

**Comment by renbaoshuo** [comment]
![](https://user-images.githubusercontent.com/22728201/77081013-fc2ef180-6a34-11ea-8644-38005bde535c.jpg)
