### ISSUE TITLE
希望第三方云储存能够支持OneDrive

### ISSUE THREAD

**Issue by hapke24** [lsky-org/lsky-pro#161]
最近在使用OneIndex搭建云盘，同时OneInde还附赠了一个基本的图床功能，使用过后感觉OneDrive的访问速度不错，由此萌生了这个想法（ps.其实就是想白嫖空间）。
除了OneIndex，Z-File、YukiDrive、OLAINDEX也是同类项目，均可获取OneDrive文件直链，在GitHub开源。
**以上所提项目开源地址：**
[OneIndex（原作者因某些原因删库，此为备份）](https://github.com/ikym/Oneindex)
[Z-File](https://github.com/zhaojun1998/zfile)
[YukiDrive](https://github.com/YukiCoco/YukiDrive)
[OLAINDEX](https://github.com/WangNingkai/OLAINDEX)

**Comment by ShaoPak** [comment]
> 最近在使用OneIndex搭建云盘，同时OneInde还附赠了一个基本的图床功能，使用过后感觉OneDrive的访问速度不错，由此萌生了这个想法（ps.其实就是想白嫖空间）。
> 除了OneIndex，Z-File、YukiDrive、OLAINDEX也是同类项目，均可获取OneDrive文件直链，在GitHub开源。
> **以上所提项目开源地址：**
> [OneIndex（原作者因某些原因删库，此为备份）](https://github.com/ikym/Oneindex)
> [Z-File](https://github.com/zhaojun1998/zfile)
> [YukiDrive](https://github.com/YukiCoco/YukiDrive)
> [OLAINDEX](https://github.com/WangNingkai/OLAINDEX)

同期待，希望可以支持世纪互联OneDrive

**Comment by Creling** [comment]
OneDrive的链接不是永久链接（所以oneindex之类的程序都有“刷新缓存”这个概念）。
如果因为要添加OneDrive后端而特意给lsky-pro加上刷新缓存功能，显然和其他存储后端的通用规范不符合。
因此个人认为lsky-pro不应添加OneDrive作为后端。

**Comment by ShaoPak** [comment]
> OneDrive的链接不是永久链接（所以oneindex之类的程序都有“刷新缓存”这个概念）。
> 如果因为要添加OneDrive后端而特意给lsky-pro加上刷新缓存功能，显然和其他存储后端的通用规范不符合。
> 此外，以OneDrive作为存储后端也存在图片打开过慢等问题，OneDrive并不是合适的图片直链存储源。
> 因此个人认为lsky-pro不应添加OneDrive作为后端。

需要刷新缓存这个问题有点麻烦，这样看添加onedrive作为存储端确实不是好方案
