### ISSUE TITLE
图片鉴黄按钮问题问题

### ISSUE THREAD

**Issue by fcwys** [lsky-org/lsky-pro#191]
希望拦截违规图片是否直接删除能在图片鉴黄配置页面添加一个开关按钮，更为方便，谢谢！

**Comment by wisp-x** [comment]
是可以直接拦截违规图片的，详见：https://www.kancloud.cn/wispx/lsky-pro/1569427

**Comment by fcwys** [comment]
意思是希望是否拦截图片这个功能，弄成一个开关在图片鉴黄设置页面呢
