### ISSUE TITLE
建议文件路径命名规则增加username

### ISSUE THREAD

**Issue by HazukiKaguya** [lsky-org/lsky-pro#198]
如标题，建议上传配置的文件路径命名规则增加{username}，便于管理

**Comment by Gahotx** [comment]
附议，建议给每个用户新增一个专属的{username}或者{uid}之类的作为文件路径命名规则选项，方便多用户图片划分

**Comment by Gahotx** [comment]
打扰一下，请问这个是已经支持了还是不弄了？@wisp-x

**Comment by wisp-x** [comment]
@Gahotx 不支持用户名，因为用户名可能是中文、字符。

**Comment by Gahotx** [comment]
> @Gahotx 不支持用户名，因为用户名可能是中文、字符。

好的，谢谢（不过用户注册时生成一个专属的uid倒是可以）

**Comment by nmgliangwei** [comment]
2.x版本支持用户id目录了
