### ISSUE TITLE
水印设置可否由用户独立配置？

### ISSUE THREAD

**Issue by HazukiKaguya** [lsky-org/lsky-pro#202]
可否由每个用户独立配置是否启用水印与水印样式？目前好像只能由所有者对不同的储存策略设置不同的水印？

**Comment by wisp-x** [comment]
不能直接针对用户设置，你可以通过用户组配置不同的策略来区分不同用户的水印设置。

**Comment by HazukiKaguya** [comment]
> 不能直接针对用户设置，你可以通过用户组配置不同的策略来区分不同用户的水印设置。

那么后续会考虑添加吗？

**Comment by wisp-x** [comment]
> > 不能直接针对用户设置，你可以通过用户组配置不同的策略来区分不同用户的水印设置。
> 
> 那么后续会考虑添加吗？

可能会
