### ISSUE TITLE
2.0 版本计划

### ISSUE THREAD

**Issue by wisp-x** [lsky-org/lsky-pro#281]
兰空图床从第一个版本开始，就使用 ThinkPHP 5.1 框架开发，经历了 19 个版本，在迭代的过程中，我尽量保持着代码的可读性与健壮性。

但回顾过往，看自己一行行写出来的代码，竟是如此的生涩。旧的东西总是要抛弃的，加之 PHP 8.1 都已经发布，为了使用更好的特性，这次的 2.0 版本，将会使用 Laravel 9 LTS 版本重写兰空图床，感谢 ThinkPHP 开发者，respect!

使用 Laravel 意味着兰空图床已无法安装在虚拟主机上，且安装条件较高，以下是硬性要求：
> - PHP >= 8.0
> - BCMath PHP 扩展
> - Ctype PHP 扩展
> - DOM PHP 拓展
> - Fileinfo PHP 扩展
> - JSON PHP 扩展
> - Mbstring PHP 扩展
> - OpenSSL PHP 扩展
> - PDO PHP 扩展
> - Tokenizer PHP 扩展
> - XML PHP 扩展
> - Imagick 拓展

新的版本将使用大名鼎鼎的 [flysystem](https://flysystem.thephpleague.com/) 实现上传策略，不再局限于旧版本需要自己适配。目前开源的实现库有且不限于这些：
- [league/flysystem-aws-s3-v3](https://github.com/thephpleague/flysystem-aws-s3-v3) AWS S3
- [league/flysystem-sftp](https://github.com/thephpleague/flysystem-sftp) SFTP
- [league/flysystem-ftp](https://github.com/thephpleague/flysystem-ftp) FTP
- [league/flysystem-webdav](https://github.com/thephpleague/flysystem-webdav) Webdav
- [league/flysystem-google-cloud-storage](https://github.com/thephpleague/flysystem-google-cloud-storage) Google Cloud Storage
- [nao-pon/flysystem-google-drive](https://github.com/nao-pon/flysystem-google-drive) Google Drive
- [spatie/flysystem-dropbox](https://github.com/spatie/flysystem-dropbox) Dropbox
- [gliterd/flysystem-backblaze](https://github.com/gliterd/flysystem-backblaze) Backblaze
- [overtrue/flysystem-qiniu](https://github.com/overtrue/flysystem-qiniu) 七牛云 Kodo
- [freyo/flysystem-qcloud-cos-v5](https://github.com/freyo/flysystem-qcloud-cos-v5) 腾讯云 COS
- [jellybool/flysystem-upyun](https://github.com/JellyBool/flysystem-upyun) 又拍云 USS
- [iidestiny/flysystem-oss](https://github.com/iiDestiny/flysystem-oss) 阿里云 OSS
...

需要注意的是，新版本的上传文件的流程依然是 本地->服务器->第三方储存。因为是重写，且数据库层面将有重大变动，旧版本无法升级到 2.0 版本。

目前新版本还在筹备调研当中，因为精力有限，旧版本只提供安全质量修复。如果你对 2.0 版本感兴趣，可以添加 [TG 群组
](https://t.me/lsky_pro) 一起探讨。

**Comment by louiejordan** [comment]
期待，2.0大概什么时候发布？

**Comment by wisp-x** [comment]
> 期待，2.0大概什么时候发布？

业余时间开发，无法预算具体发布时间，不过开发过程中会使用 github 的 [项目看板](https://github.com/wisp-x/lsky-pro/projects/1)，关注这个即可。

**Comment by fcwys** [comment]
希望能有一个数据库迁移指南或工具

**Comment by wisp-x** [comment]
> 希望能有一个数据库迁移指南或工具

比较困难，我尽量，现在已经确定的是旧版本的用户密码、文件夹无法迁移。

**Comment by Smalltred** [comment]
希望能新版本能有一个全新的UI

**Comment by HazukiKaguya** [comment]
> > 希望能有一个数据库迁移指南或工具
> 
> 比较困难，我尽量，现在已经确定的是旧版本的用户密码、文件夹无法迁移。

也就是每个用户绑定的图片信息是可以迁移的？那就够了。

**Comment by zdvas** [comment]
这个迁移的过程小白看不懂呀，有没有视频的演示，最怕数据库不会备份，挂了
