### ISSUE TITLE
一点点的功能建议

### ISSUE THREAD

**Issue by akatsukiro** [lsky-org/lsky-pro#288]
图床是公开的，可能会碰到上传不当图片的人，希望能添加如封禁用户（数天/月）、一键查找、替换、删除该用户数据（包括图片）的功能。现在只有删除用户的功能，图片不删，弄起来还是有些麻烦的。
然后搜索功能希望能搜索上传者名称，不止图片名（搜图片名有些情况下还挺反人类的）。

**Comment by wisp-x** [comment]
删除用户同时删除该用户图片，目前来说是不会考虑实现这个特性的，试想如果你使用的是第三方储存，某个用户有10w+的图片，第三方储存没有提供批量删除接口，要如何去删除这么多的图片？
