### ISSUE TITLE
一个图片上传的小Bug

### ISSUE THREAD

**Issue by akatsukiro** [lsky-org/lsky-pro#293]
复制上传图片时快速多次点击确定稳定触发。
具体：单击确定后提示框消失，此时尽快点击，待上传的图片会闪烁一下然后变成这样。（逃课打法：双击确定）
![image](https://user-images.githubusercontent.com/69096852/148737832-c2f55ae0-7612-4986-a973-a64c93e6064f.png)
就会像这样卡住。
V 1.6.4

**Comment by wisp-x** [comment]
没看懂，确定选择后尽快点击上传按钮？

**Comment by akatsukiro** [comment]
啊，不是的。
复制图片后上传的话是自动上传的。
![image](https://user-images.githubusercontent.com/69096852/148744141-6936cb1c-d31e-48f2-a036-571b9da83484.png)
这个对话框，“双击”确定就会触发这个bug。
