### ISSUE TITLE
开启鉴黄后出现SSL错误

### ISSUE THREAD

**Issue by ssyximmlove** [lsky-org/lsky-pro#298]
![image](https://user-images.githubusercontent.com/23517759/153112536-73a517c8-7b63-4334-984c-88154ae583c7.png)
cURL error 60: SSL certificate problem: certificate has expired (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
Lsky版本v1.6.4
php版本7.4.27

**Comment by qitayun** [comment]
同样的问题。解决了吗

**Comment by qiqiblog** [comment]
1、下载https://curl.se/ca/cacert.pem
2、复制cacert.pem中的内容替换/etc/ssl/certs/ca-bundle.crt的内容并保存
