### ISSUE TITLE
希望添加更加多样和通用的远程存储方式

### ISSUE THREAD

**Issue by aiwush** [lsky-org/lsky-pro#301]
例如SFTP/Webdav等，现有的ftp存储方式不够灵活，在路径选择等方式不够自由无法进行选择。域名希望能通过lsky进行反代，否则将存储空间设置为nas或者网盘无法直接通过域名访问

**Comment by Cinnamoroll-cat** [comment]
支持onedrive吗

**Comment by Cinnamoroll-cat** [comment]
这是个好项目
