### ISSUE TITLE
不支持redis吗

### ISSUE THREAD

**Issue by qitayun** [lsky-org/lsky-pro#302]
我一打开就访问不了
关了就恢复了
php7.2
redis6.2.4

**Comment by wisp-x** [comment]
程序并没有用到 redis

**Comment by qitayun** [comment]
php中的redis啊
不兼容

---原始邮件---
发件人: "Wisp ***@***.***&gt;
发送时间: 2022年2月15日(周二) 上午6:22
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wisp-x/lsky-pro] 不支持redis吗 (Issue #302)




 
程序并没有用到 redis
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
