### ISSUE TITLE
修改上传大小后就会出现这个，有谁懂啥原因吗

### ISSUE THREAD

**Issue by wb-Joy** [lsky-org/lsky-pro#309]
[ThinkPHP](http://www.thinkphp.cn/) V5.1.41 LTS { 十年磨一剑-为API开发设计的高性能框架 }

**Comment by wb-Joy** [comment]
![image](https://user-images.githubusercontent.com/89234190/155985369-cd57cd84-18be-4587-b7ac-d60b9664f699.png)

**Comment by wisp-x** [comment]
编辑根目录的 `.env` 文件，把 debug 改为 true 可以看到详细的错误信息。
