### ISSUE TITLE
修改了上传大小限制为50M传10M的文件提示文件过大

### ISSUE THREAD

**Issue by Twiyin0** [lsky-org/lsky-pro#310]
作者大大，我在系统设置里面设置了限制图片上传大小为50M，服务器php限制的上传大小为100M，但上传10M的图片的时候报错说图片过大
![image](https://user-images.githubusercontent.com/87588281/156696303-0431da1f-ea0a-4458-8edf-e6060e1529b1.png)
储存策略是无论是本地还是又拍云USS都不能上传大于10M的图片
修改上传限制大小为4.88G也还是不行
![image](https://user-images.githubusercontent.com/87588281/156696764-7d024c8d-7217-4444-b4b5-408cbaa25fe0.png)
请问这个需要在源码里面修改吗？
如果可以的话，希望在环境变量里面加一个能限制上传文件大小项
辛苦作者大大

**Comment by wisp-x** [comment]
检查是否因为 cdn 所导致，除了修改 php 上传大小限制，php 的 最大 post 数据限制也需要更改。

**Comment by Twiyin0** [comment]
没有挂CDN，php最大post数据限制也是100M

**Comment by wisp-x** [comment]
那就重启 php 再试，确认配置是否正确被修改了、检查服务器防火墙等。图中的错误提示 Request file size too large 并不是兰空图床抛出的。

**Comment by Twiyin0** [comment]
啊，好了，把鉴黄关掉就可以了，应该是鉴黄那边不支持大于10M的图片，谢谢大大
