### ISSUE TITLE
希望增加自定义后缀

### ISSUE THREAD

**Issue by HazukiKaguya** [lsky-org/lsky-pro#313]
希望增加自定义后缀，或者追加mp4 webm格式上传

**Comment by HazukiKaguya** [comment]
对了，还有控制台会出现500错误

**Comment by wisp-x** [comment]
> 对了，还有控制台会出现500错误

编辑根目录的 .env 文件，截图发一下详细的错误信息

**Comment by HazukiKaguya** [comment]
> > 对了，还有控制台会出现500错误
> 
> 编辑根目录的 .env 文件，debug 改为 true，截图发一下详细的错误信息
好的，我试试。
顺便直接粘贴上传剪切板图片没了吗？

**Comment by HazukiKaguya** [comment]
![image](https://user-images.githubusercontent.com/35645329/158031661-4252c486-a43b-4f08-ae6a-bba19cbee7bd.png)

**Comment by wisp-x** [comment]
粘贴剪贴板上传是有的

**Comment by HazukiKaguya** [comment]
![image](https://user-images.githubusercontent.com/35645329/158031759-460a736c-7c8d-420f-b5d9-7bd0d8daa3a2.png)
![image](https://user-images.githubusercontent.com/35645329/158031766-11a3442b-d1aa-4d1d-811b-7e4ee98906cb.png)
怪了

**Comment by HazukiKaguya** [comment]
首页和上传图片页都没看到OTZ

**Comment by wisp-x** [comment]
这个报错，请修改 
https://github.com/lsky-org/lsky-pro/blob/47db995a5456d73f8f9b83f596a1d18671dc2309/app/Utils.php#L123
改为：
```php
 public static function shortenNumber(int|string $n, int $precision = 1): int|string
```

**Comment by HazukiKaguya** [comment]
> 这个报错，请修改
> 
> https://github.com/lsky-org/lsky-pro/blob/47db995a5456d73f8f9b83f596a1d18671dc2309/app/Utils.php#L123
> 
> 
> 改为：
> ```
>  public static function shortenNumber(int|string $n, int $precision = 1): int|string
> ```

感谢，这个ok了，辛苦作者大大了。粘贴剪贴板上传还是没有看到。

**Comment by HazukiKaguya** [comment]
顺便上传数量限制设置为0是否就是不限制上传？

**Comment by wisp-x** [comment]
> 顺便上传数量限制设置为0是否就是不限制上传？

是的

粘贴上传，处在上传页面，按下粘贴快捷键即可。

**Comment by HazukiKaguya** [comment]
> 

哦哦，了解了。之后会考虑追加上传框右键粘贴吗？

**Comment by HazukiKaguya** [comment]
> > 顺便上传数量限制设置为0是否就是不限制上传？
> 
> 是的
> 
> 粘贴上传，处在上传页面，按下粘贴快捷键即可。

![image](https://user-images.githubusercontent.com/35645329/158033473-2b24760c-1b5c-48e6-9d8f-8ea0543a712e.png)
后台邮箱和用户名的表单是不是名称写反了？

**Comment by wisp-x** [comment]
是写反了，昨晚修复过然后重新打包了，下载最新版本替换一下 app和resources目录即可

**Comment by HazukiKaguya** [comment]
> 希望增加自定义后缀，或者追加mp4 webm格式上传

尝试按照修复tif、ico的方法修改以后，上传到最后显示
Unable to read image from path (/tmp/phpXXXXXX).
看起来似乎是程序只允许了image格式的上传？（调用的是php上传图片的方法？）

**Comment by wisp-x** [comment]
> > 是写反了，昨晚修复过然后重新打包了，下载最新版本替换一下 app和resources目录即可
> 
> 尝试按照修复tif、ico的方法修改mp4上传以后，上传到最后显示 Unable to read image from path (/tmp/phpXXXXXX). 看起来似乎是程序只允许了image格式的上传？（调用的是php上传图片的方法？）

只允许上传图片。

**Comment by HazukiKaguya** [comment]
> > > 是写反了，昨晚修复过然后重新打包了，下载最新版本替换一下 app和resources目录即可
> > 
> > 
> > 尝试按照修复tif、ico的方法修改mp4上传以后，上传到最后显示 Unable to read image from path (/tmp/phpXXXXXX). 看起来似乎是程序只允许了image格式的上传？（调用的是php上传图片的方法？）
> 
> 只允许上传图片。

请问如何修改可以上传视频的呢？这边对上传视频有一定需求OTZ

**Comment by wisinfun** [comment]
> > > > 是写反了，昨晚修复过然后重新打包了，下载最新版本替换一下 app和resources目录即可
> > > 
> > > 
> > > 尝试按照修复tif、ico的方法修改mp4上传以后，上传到最后显示 Unable to read image from path (/tmp/phpXXXXXX). 看起来似乎是程序只允许了image格式的上传？（调用的是php上传图片的方法？）
> > 
> > 
> > 只允许上传图片。
> 
> 请问如何修改可以上传视频的呢？这边对上传视频有一定需求OTZ

也有mp4视频的需求，也有svg格式的需求

**Comment by HazukiKaguya** [comment]
> > > > > 是写反了，昨晚修复过然后重新打包了，下载最新版本替换一下 app和resources目录即可
> > > > 
> > > > 
> > > > 尝试按照修复tif、ico的方法修改mp4上传以后，上传到最后显示 Unable to read image from path (/tmp/phpXXXXXX). 看起来似乎是程序只允许了image格式的上传？（调用的是php上传图片的方法？）
> > > 
> > > 
> > > 只允许上传图片。
> > 
> > 
> > 请问如何修改可以上传视频的呢？这边对上传视频有一定需求OTZ
> 
> 也有mp4视频的需求，也有svg格式的需求

https://github.com/lsky-org/lsky-pro/pull/338
不完善，支持mp4,webm上传
画廊与管理员的图片管理页面应该已经支持mp4,webm直接查看/播放，个人用户的图片管理页面暂不支持，因为不知道咋改。
供想要支持其他类型文件上传的人参考如何修改。

**Comment by wisinfun** [comment]
> #338 不完善，支持mp4,webm上传 画廊与管理员的图片管理页面应该已经支持mp4,webm直接查看/播放，个人用户的图片管理页面暂不支持，因为不知道咋改。 供想要支持其他类型文件上传的人参考如何修改。

再请教下，2.0也支持mp4上传吗，还是1.X才支持？
我刚安装了2.0，没看到相关设置项，1.X还没用过

**Comment by wisinfun** [comment]
> #338 不完善，支持mp4,webm上传 画廊与管理员的图片管理页面应该已经支持mp4,webm直接查看/播放，个人用户的图片管理页面暂不支持，因为不知道咋改。 供想要支持其他类型文件上传的人参考如何修改。

能支持上传已经很满足了，感谢
是要等新版本么，还是对照着改文件

**Comment by HazukiKaguya** [comment]
> > #338 不完善，支持mp4,webm上传 画廊与管理员的图片管理页面应该已经支持mp4,webm直接查看/播放，个人用户的图片管理页面暂不支持，因为不知道咋改。 供想要支持其他类型文件上传的人参考如何修改。
> 
> 能支持上传已经很满足了，感谢 是要等新版本么，还是对照着改文件

对照着差异改文件。
https://github.com/lsky-org/lsky-pro/compare/master...HazukiKaguya:master
试试这个链接可以访问吗？
更新追加了admin的图片管理页面的点击图片弹出的弹窗的支持webm、mp4播放支持

**Comment by HazukiKaguya** [comment]
> 能支持上传已经很满足了，感谢 是要等新版本么，还是对照着改文件

少改了一个/app/Http/Requests/Admin)/GroupRequest.php，也得改，直接看上一条的差异，跟着改应该就行了

**Comment by HazukiKaguya** [comment]
> > > 是写反了，昨晚修复过然后重新打包了，下载最新版本替换一下 app和resources目录即可
> > 
> > 
> > 尝试按照修复tif、ico的方法修改mp4上传以后，上传到最后显示 Unable to read image from path (/tmp/phpXXXXXX). 看起来似乎是程序只允许了image格式的上传？（调用的是php上传图片的方法？）
> 
> 只允许上传图片。

对了，tiff格式（tif是tiff的简写形式,两者意义相同）能否添加一下？

**Comment by wisinfun** [comment]
> > 能支持上传已经很满足了，感谢 是要等新版本么，还是对照着改文件
> 
> 少改了一个/app/Http/Requests/Admin)/GroupRequest.php，也得改，直接看上一条的差异，跟着改应该就行了

哈哈，尝试了两次，失败了，后台格式能看到mp4了，但是保存的时候报错，上传mp4文件时也报错了

**Comment by wisinfun** [comment]
> > 哈哈，尝试了两次，失败了，后台格式能看到mp4了，但是保存的时候报错，上传mp4文件时也报错了
> 
> /app/Http/Requests/Admin)/GroupRequest.php 的request请求没改，要加上否则保存不了 ![image](https://user-images.githubusercontent.com/35645329/159963272-d827de01-0e65-486d-8db2-d0c746a4f81f.png) 上传报错如果是生成缩略图报错的话看看resources/views/components/upload.blade.php 这个的缩略图显示相关代码有没有改 resources/views/components/upload.blade.php ![image](https://user-images.githubusercontent.com/35645329/159963403-25efa58c-0121-4fd8-ae6a-8186243a2fc6.png)

是这么操作的
<img width="1147" alt="CleanShot 2022-03-28 at 13 43 44@2x" src="https://user-images.githubusercontent.com/41355260/160333802-4cd5f3e2-a705-4612-a8b2-543d37f13027.png">
<img width="1039" alt="CleanShot 2022-03-28 at 13 45 57@2x" src="https://user-images.githubusercontent.com/41355260/160333925-15fa4a76-da0d-413b-a9fd-c2769c771c78.png">

**Comment by nanbowan323** [comment]
> > > #338 不完善，支持mp4,webm上传 画廊与管理员的图片管理页面应该已经支持mp4,webm直接查看/播放，个人用户的图片管理页面暂不支持，因为不知道咋改。 供想要支持其他类型文件上传的人参考如何修改。
> 
> > 
> 
> > 能支持上传已经很满足了，感谢 是要等新版本么，还是对照着改文件
> 
> 
> 
> 对照着差异改文件。
> 
> https://github.com/lsky-org/lsky-pro/compare/master...HazukiKaguya:master
> 
> 试试这个链接可以访问吗？
> 
> 更新追加了admin的图片管理页面的点击图片弹出的弹窗的支持webm、mp4播放支持
> 
> 其他格式的也可以试试根据这个思路改看看能不能支持

大佬，我用的是2.1的版本，根据这个方法修改后视频上传成功，引用到markdown也正常预览。但是我的相册页面一张图都不显示了，另外图片管理页面的图片也无法正常显示。并且以前文章引用的图片也不显示了。能提供下2.1版本的修改方式吗？

**Comment by HazukiKaguya** [comment]
> > > > #338 不完善，支持mp4,webm上传 画廊与管理员的图片管理页面应该已经支持mp4,webm直接查看/播放，个人用户的图片管理页面暂不支持，因为不知道咋改。 供想要支持其他类型文件上传的人参考如何修改。
> > 
> > 
> > > 
> > 
> > 
> > > 能支持上传已经很满足了，感谢 是要等新版本么，还是对照着改文件
> > 
> > 
> > 对照着差异改文件。
> > [master...HazukiKaguya:master](https://github.com/lsky-org/lsky-pro/compare/master...HazukiKaguya:master)
> > 试试这个链接可以访问吗？
> > 更新追加了admin的图片管理页面的点击图片弹出的弹窗的支持webm、mp4播放支持
> > 其他格式的也可以试试根据这个思路改看看能不能支持
> 
> 大佬，我用的是2.1的版本，根据这个方法修改后视频上传成功，引用到markdown也正常预览。但是我的相册页面一张图都不显示了，另外图片管理页面的图片也无法正常显示。并且以前文章引用的图片也不显示了。能提供下2.1版本的修改方式吗？

是不是非原图显示的？这样修改似乎可能会干掉非原图显示？你看看修改不要修改涉及到图片预览图显示的代码，或者写个条件语句让它只对新添加的格式生效（
2.1的修改等我有空看看。

**Comment by zdoek001** [comment]
> > > > > #338 不完善，支持mp4,webm上传 画廊与管理员的图片管理页面应该已经支持mp4,webm直接查看/播放，个人用户的图片管理页面暂不支持，因为不知道咋改。 供想要支持其他类型文件上传的人参考如何修改。
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > 能支持上传已经很满足了，感谢 是要等新版本么，还是对照着改文件
> > > 
> > > 
> > > 对照着差异改文件。
> > > [master...HazukiKaguya:master主人。。。别忘了：师父](https://github.com/lsky-org/lsky-pro/compare/master...HazukiKaguya:master)
> > > 试试这个链接可以访问吗？
> > > 更新追加了admin的图片管理页面的点击图片弹出的弹窗的支持webm、mp4播放支持
> > > 其他格式的也可以试试根据这个思路改看看能不能支持
> > 
> > 
> > 大佬，我用的是2.1的版本，根据这个方法修改后视频上传成功，引用到markdown也正常预览。但是我的相册页面一张图都不显示了，另外图片管理页面的图片也无法正常显示。并且以前文章引用的图片也不显示了。能提供下2.1版本的修改方式吗？
> 
> 是不是非原图显示的？这样修改似乎可能会干掉非原图显示？你看看修改不要修改涉及到图片预览图显示的代码，或者写个条件语句让它只对新添加的格式生效（ 2.1的修改等我有空看看。

后面还有研究这个mp4吗。也有需求。，

**Comment by doubi666** [comment]
> > > > > #338不完美，支持mp4,webm上传画廊与管理员的图片管理页面应该已经支持mp4,webm直接查看/播放，个人用户的图片管理页面暂时不支持，因为不知道咋改。求支持其他修改类型文件上传的人参考如何。
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > 能支持上传已经很满意了，谢谢是要等新版本么，还是对照着改文件
> > > 
> > > 
> > > 
> > > [master...HazukiKaguya:master](https://github.com/lsky-org/lsky-pro/compare/master...HazukiKaguya:master)
> > > 试试这个链接可以访问吗？
> > > 更新追加了admin的图片管理页面的点击图片弹出的弹窗的支持webm、mp4播放支持其他
> > > 格式的也可以试试根据这个想法改看看能不能支持
> > 
> > 
> > 大佬，我用的是2.1的版本，按照这个方法修改后视频上传成功，引用到markdown也能正常预览。但是我的相册页面一张图都没有显示了，其他图片管理页面的图片也无法正常显示。并且修改之前文章引用的图片也不显示了。能提供下2.1版本的方式吗？
> 
> 是不是非原图显示的？这样修改好像可能会干掉非原图显示？你看看修改不要涉及到图片预览图显示的代码，或者写个条件语句只使对新添加的格式生效（ 2.1的修改等我有空看看。

后面还有研究嘛 发现改了2.1以后有很多问题。。。。 fork你的版本用起来没有新版本好使
