### ISSUE TITLE
相册中显示图片数量不全

### ISSUE THREAD

**Issue by vlssu** [lsky-org/lsky-pro#315]
如题，在2.0中，我将以前的数据导入到新版后，新建了一个相册，将1000张图片移动到一个相册中，但是显示的图片只有40张
建议添加全选图片的功能（我是直接从数据库改，毕竟图片量大）
我在移动相册·的时候手动移动和数据库修改都试过了，都是显示图片不全，或许你可以看看？

可以将画廊设为公开吗，（还有随机图，虽然我自己写了一个，但是需要定时运行一个程序）

还有在迁移的时候，图片尺寸他获取失败了，可以弄个重新（校准）尺寸吗

**Comment by wisp-x** [comment]
这个问题已经修复了，请下载最新版本 https://github.com/lsky-org/lsky-pro/releases/download/2.0/lsky-pro-2.0.zip，然后替换
`app`、`resources`、`public/css`、`public/js`目录，注意不要直接覆盖 public 目录。

画廊暂时不能设置为公开，后续版本会考虑，届时可以直接后台升级。
图片尺寸重新校准，那只能自己写脚本了。
