### ISSUE TITLE
静态资源加载失败

### ISSUE THREAD

**Issue by fcwys** [lsky-org/lsky-pro#317]
![image](https://user-images.githubusercontent.com/28641034/158046958-6477ea6c-d143-48df-92a0-550bae1aaff1.png)

**Comment by wisp-x** [comment]
请求域名是反代的吗？

**Comment by fcwys** [comment]
是的

**Comment by wisp-x** [comment]
应该是 cdn 的问题，估计与 cdn 返回的 headers 有关，但是你可以强行指定静态资源域名，编辑 `.env` 文件，追加一行：
```
ASSET_URL=https://你的域名
```

**Comment by fcwys** [comment]
好的，我试试

**Comment by fcwys** [comment]
界面正常了，但是图片加载失败
![image](https://user-images.githubusercontent.com/28641034/158048109-d1c3c157-7bd8-4e08-a582-e8a58c5febfc.png)

**Comment by wisp-x** [comment]
忘了...静态资源变成 https 了，但是接口域名还是 http 的。那你只能修改代码了。
在这个文件的 boot 方法里
https://github.com/lsky-org/lsky-pro/blob/6d0631b494c31788396cb948f691fe542e5bf8b4/app/Providers/AppServiceProvider.php#L31-L52

第 32 行下面追加一行：
`\Illuminate\Support\Facades\URL::forceScheme('https');`

**Comment by fcwys** [comment]
好的，谢谢

**Comment by fcwys** [comment]
经过测试可以了，希望下个版本修复下呢，辛苦！

**Comment by Cinnamoroll-cat** [comment]
实际上，使用cdn请使用https回源。反代则代理加密的https即可。否则将会出现此问题。这并不是程序的问题，而是由于操作有误造成。

**Comment by Soulballad** [comment]
> 忘了...静态资源变成 https 了，但是接口域名还是 http 的。那你只能修改代码了。 在这个文件的 boot 方法里
> 
> https://github.com/lsky-org/lsky-pro/blob/6d0631b494c31788396cb948f691fe542e5bf8b4/app/Providers/AppServiceProvider.php#L31-L52
> 
> 第 32 行下面追加一行： `\Illuminate\Support\Facades\URL::forceScheme('https');`

我也遇到了跨域问题，使用此方法解决了

**Comment by leoneoo** [comment]
我是设置了反向代理后，https访问后，网页无法正常浏览，使用此方法设置后，https访问正常了。感谢！！！

**Comment by hausen1012** [comment]
bug还没解决吗？

**Comment by zhaoguo2008** [comment]
我添加代码，但是没有反应，登陆还是乱的

**Comment by wleelw** [comment]
> 

请问我有两个域名能够同时添加吗？
