### ISSUE TITLE
浏览器支持

### ISSUE THREAD

**Issue by HazukiKaguya** [lsky-org/lsky-pro#318]
目前IE和火狐似乎会不断转圈动不了而且样式有问题。
还有我的图片这个页面的预览图如何修改直接使用原始图片资源？目前用缩略图这边cloudflare没缓存有用户反馈反而速度拖慢了很多OTZ
![image](https://user-images.githubusercontent.com/35645329/158047617-f69188a2-9332-44f8-8099-032c7cdc6c2e.png)
![image](https://user-images.githubusercontent.com/35645329/158047733-33c3e734-01bb-49d1-8178-82751a65e4e7.png)

**Comment by wisp-x** [comment]
只支持市面上较新的主流浏览器。

**Comment by HazukiKaguya** [comment]
> 只支持市面上较新的主流浏览器。

好的，看来只能让ie用户换浏览器或者用api写个ie能用的上传页面了2333
![image](https://user-images.githubusercontent.com/35645329/158052687-537baead-c15b-4a4d-afd2-b52799805e98.png)

顺便这边更改以后邮箱和名称的表单名称显示还是反过来的
![image](https://user-images.githubusercontent.com/35645329/158052552-851d3ee6-1f4f-4726-a912-8ebebf62d8e4.png)

**Comment by wisp-x** [comment]
> > 只支持市面上较新的主流浏览器。
> 
> 好的，看来只能让ie用户换浏览器或者用api写个ie能用的上传页面了2333 ![image](https://user-images.githubusercontent.com/35645329/158052687-537baead-c15b-4a4d-afd2-b52799805e98.png)
> 
> 顺便这边更改以后邮箱和名称的表单名称显示还是反过来的 ![image](https://user-images.githubusercontent.com/35645329/158052552-851d3ee6-1f4f-4726-a912-8ebebf62d8e4.png)

下载最新版本 覆盖 resources 文件夹

**Comment by HazukiKaguya** [comment]
> > > 只支持市面上较新的主流浏览器。
> > 
> > 
> > 好的，看来只能让ie用户换浏览器或者用api写个ie能用的上传页面了2333 ![image](https://user-images.githubusercontent.com/35645329/158052687-537baead-c15b-4a4d-afd2-b52799805e98.png)
> > 顺便这边更改以后邮箱和名称的表单名称显示还是反过来的 ![image](https://user-images.githubusercontent.com/35645329/158052552-851d3ee6-1f4f-4726-a912-8ebebf62d8e4.png)
> 
> 下载最新版本 覆盖 resources 文件夹

奇了怪了，鬼知道是啥缓存，我网站程序这里确实也没问题啊，无伤大雅不管了，说不定啥时候就好了2333
![image](https://user-images.githubusercontent.com/35645329/158056787-e8cee9f6-e9a1-4481-9e5e-3f1ccf96f284.png)
