### ISSUE TITLE
图片鉴黄等配置文档和操作流程

### ISSUE THREAD

**Issue by ovenslove** [lsky-org/lsky-pro#322]
![image](https://user-images.githubusercontent.com/11400029/158101336-ca8d7866-6e5b-438b-9764-71ae6f80f66e.png)
这个功能的相关文档有没有呢？这些参数怎么获取

**Comment by wisp-x** [comment]
文档还在完善中

**Comment by ovenslove** [comment]
@wisp-x 可以在这里简短告知一下，这个参数获取途径或者阿里云相关的文档

**Comment by ovenslove** [comment]
阿里云端配置账号需要什么权限才能使用，我现在报错  上传失败, Scan: detect not success. code:596

**Comment by wisp-x** [comment]
首先需要去开通阿里云内容审核服务：
https://www.aliyun.com/product/lvwang
业务场景对应内容安全控制台中的 -> 设置 -> 机器审核 -> 业务场景

地域目前阿里云支持：
- cn-shanghai：华东2（上海）
- cn-beijing：华北2（北京）
- cn-shenzhen：华南1（深圳）
- ap-southeast-1：新加坡

**Comment by ovenslove** [comment]
@wisp-x 要给ram账号添加  
AliyunYundunGreenWebFullAccess
权限才不会报错
