### ISSUE TITLE
支持自适应访问协议

### ISSUE THREAD

**Issue by fcwys** [lsky-org/lsky-pro#323]
希望支持自定义访问协议（http或https），或是统一一个参数配置入口设置全站接口及静态资源的访问协议或地址，谢谢！

下图中站点是https但接口文档仍是http协议：
![image](https://user-images.githubusercontent.com/28641034/158115119-670cb440-c724-4051-80d1-b9d8c234d735.png)

**Comment by wisp-x** [comment]
这是你自己使用反代出现的问题。
