### ISSUE TITLE
V2.0版本，腾讯云存储策略上传出现错误

### ISSUE THREAD

**Issue by rayooss** [lsky-org/lsky-pro#324]
![image](https://user-images.githubusercontent.com/99969898/158119221-bd6bcaa1-ae8b-4828-a59c-1cac9ae72c25.png)
如图，使用的是腾讯云存储策略，上传时提示：上传失败, 服务异常，请稍后再试
我非常确认我腾讯云的信息填写正确
以下是用户组配置：
![image](https://user-images.githubusercontent.com/99969898/158119383-3fb64700-8f99-49df-a771-edcff57e3c9b.png)
以下是存储策略的配置，部分配置由于隐私原因，已打码：
![image](https://user-images.githubusercontent.com/99969898/158119574-0d55ec16-fd44-4473-bf11-bc5864933294.png)
但是，神奇的是，使用本地的存储策略却可以正常上传并处理文件！

**Comment by wisp-x** [comment]
检查储存桶名称，假设：test-12345678，前面的 test 才是储存桶名称，后面的数字是 appid

**Comment by rayooss** [comment]
OK

**Comment by rayooss** [comment]
已解决，感谢！
