### ISSUE TITLE
扩展插件需要适配 "manifest_version": 3

### ISSUE THREAD

**Issue by szkzn** [lsky-org/lsky-pro#327]
你好，开发者，不好意思重复提了 issue（你可能遗忘了 扩展插件那个仓库下面的issue了），在 Chrome v99.x 稳定版 x64 上面扩展程序无法正常加载并报错：https://github.com/lsky-org/lsky-pro-chrome-extension/issues/7

个人尝试简单粗暴改了值为 3 无法加载......能否修复一下吗

**Comment by szkzn** [comment]
https://developer.chrome.com/blog/mv2-transition/

**Comment by szkzn** [comment]
遗漏的额外信息：
兰空图床 v1.6.4
使用本地存储策略，未使用其他存储方式，仅服务器本地硬盘存储
账号密码填写正确无误，点击扩展的历史记录能正确调用api到最后一次的上传外链
故障表现为：
上传一张图片，扩展此时会长时间卡在 正在上传 这个进程，检查系统流量，并未发现产生了上传行为，因为没有上传速度波动，会卡个几十秒的正在上传，随后上传对话框会自动自己消失，倒回去检查 图床，发现没有图片上传成功

其他排查措施：关闭了代理类扩展插件，浏览器改为直连，未使用系统代理，不通过插件上传改为网站上传能成功。

**Comment by wisp-x** [comment]
已经更新了。
