### ISSUE TITLE
ios post 请求upload接口出现CSRF token mismatch. 

### ISSUE THREAD

**Issue by Wangmafei** [lsky-org/lsky-pro#329]
ios post 请求upload接口出现CSRF token mismatch.

**Comment by wisp-x** [comment]
此错误是 csrf 攻击防范机制，但只有在网页端生效，请检查接口地址是否正确。

**Comment by wisp-x** [comment]
![image](https://user-images.githubusercontent.com/22728201/159034958-eeba84b5-e145-4c76-a844-75c231f60e35.png)
