### ISSUE TITLE
关于图片鉴定的问题

### ISSUE THREAD

**Issue by yunxixiaowu** [lsky-org/lsky-pro#331]
使用兰空pro角色组内图片识别鉴黄涉政鉴定功能，确实可以有效拦截，但只限于前台违规内容无显示，使用七牛云储存时（其他无测试），涉及违规图片还是会上传到七牛空间内，不能有效阻止上传，希望更新bug，在用户上传违规图片时，可以进行有效拦截，避免上传储存空间

**Comment by yunxixiaowu** [comment]
![Uploading Screenshot_20220317_131410.jpg…]()

**Comment by yunxixiaowu** [comment]
![Uploading Screenshot_20220317_131410.jpg…]()

**Comment by wisp-x** [comment]
七牛云官方 sdk 目前存在 bug，会导致图片无法删除，正常情况下出现违规图片不管是哪个储存都可以正常删除。等修复即可。
详见：https://github.com/qiniu/php-sdk/issues/379
