### ISSUE TITLE
创建本地存储策略，报错服务异常

### ISSUE THREAD

**Issue by Mhy278** [lsky-org/lsky-pro#333]
网页文件路径在 /www/wwwroot/img.fastmirror.net
因为挂载了数据盘 /data，所以想新建一个本地存储策略，把一部分用户的图片存在 /data/lskypro/uploads 里，但是出现了报错如下：
![error](https://user-images.githubusercontent.com/20696190/159160978-6654a8a8-db68-441b-9327-65e3e2554db0.png)
通过debug模式查看实际原因为“储存路径不存在”。
![debug](https://user-images.githubusercontent.com/20696190/159160975-551ffb8e-b684-4874-822f-68f68ca28996.png)
但实际上储存路径是存在的，且权限为777。
![dir](https://user-images.githubusercontent.com/20696190/159160977-b3d32caa-ed4d-4730-be37-40c62c94548f.png)
目前网站除了创建本地存储策略有问题外，其他无任何异常情况。

**Comment by wisp-x** [comment]
请尝试关闭防跨站攻击(open_basedir)

**Comment by Mhy278** [comment]
已经解决，非常感谢！

另外，我似乎没有找到针对用户组的空间配额管理，不知道是设计如此吗？个人觉得还是有必要增加对用户组整个进行配额管理功能的。
