### ISSUE TITLE
请问下2.0的版本怎么生成 Token

### ISSUE THREAD

**Issue by Jack-Ywn** [lsky-org/lsky-pro#336]
#### 用户邮箱和用户密码我进行替换（使用的是我注册时候的用户邮箱和用户密码）

```
https://images.yangwn.top/api/v1/tokens?email=用户邮箱&password=用户密码
```

#### 我尝试在游览器中访问上面的链接，报错如下图
![image](https://user-images.githubusercontent.com/72083949/159216378-4fcddfea-3b44-4a4f-a2f4-e1fd5fdf5023.png)

**Comment by wisp-x** [comment]
## cURL
```shell
curl --location --request POST 'https://pic.iqy.ink/api/v1/tokens' \
--form 'email="your email address"' \
--form 'password="password"'
```

## Shell wget
```shell
wget --no-check-certificate --quiet \
  --method POST \
  --timeout=0 \
  --header '' \
  --body-data 'email=your email address&password=password' \
   'https://pic.iqy.ink/api/v1/tokens'
```
## 使用 Postman
<img width="1008" alt="image" src="https://user-images.githubusercontent.com/22728201/159217649-32fdd9bc-e84f-422b-bc9c-97a9288d5672.png">

## 使用在线工具
![image](https://user-images.githubusercontent.com/22728201/159217512-54e17f48-a20d-476b-ba75-04070677c99b.png)

**Comment by Gahotx** [comment]
提示email不能为空是什么情况？
![image](https://user-images.githubusercontent.com/53534938/160229200-252ed52f-f48a-4b12-bba0-decac42384a9.png)

**Comment by Gahotx** [comment]
请问怎么查看生成了的token和怎么删除？我用api在线的工具删除会提示Unauthenticated然后重定向到登录页面

**Comment by 1039009892** [comment]
太有用啦，感谢！

**Comment by 1039009892** [comment]
太有用啦，感谢！

**Comment by 1039009892** [comment]
您好，我已收到邮件，将尽快查看。
