### ISSUE TITLE
建议将静态资源存放到`/assets`目录下

### ISSUE THREAD

**Issue by Licoy** [lsky-org/lsky-pro#345]
如题，现在的`js`及`css`和字体静态资源等访问路径都是根路径下，如果要配置缓存规则就需要两条或以上，所以建议将静态资源归类到`/assets`下，以方便做缓存策略

**Comment by Cinnamoroll-cat** [comment]
静态资源在`/resources`里面，而html文件在`/resources/view`里，基于thinkphp的项目静态文件很少有放在`/assets`下的

**Comment by Licoy** [comment]
@Cinnamoroll-cat 我指的是`/public`目录下的静态资源，另外现在2.x的版本是基于`laravel`构建的。

**Comment by Cinnamoroll-cat** [comment]
> @Cinnamoroll-cat 我指的是`/public`目录下的静态资源，另外现在2.x的版本是基于`laravel`构建的。

哦，我知道了，想法不错，修改的地方是不少。
