### ISSUE TITLE
请问可以对接Pic Go软件吗？

### ISSUE THREAD

**Issue by codesbuff** [lsky-org/lsky-pro#346]
请问大佬，2.X版本以后能支持Pic Go上传图片吗？刚刚看了下有1.0版本的插件已经不能用了。

**Comment by wisp-x** [comment]
![image](https://user-images.githubusercontent.com/22728201/159656823-8a5325a1-7590-4502-b468-4a5a56e3b9c2.png)

**Comment by hellodk34** [comment]
你好 @codesbuff ，我写了这个插件 https://github.com/hellodk34/picgo-plugin-lankong 欢迎使用

**Comment by codesbuff** [comment]
> 你好@codesbuff，我写了这个插件https://github.com/hellodk34/picgo-plugin-lankong欢迎使用

非常感谢大佬

**Comment by codesbuff** [comment]
> ![图片](https://user-images.githubusercontent.com/22728201/159656823-8a5325a1-7590-4502-b468-4a5a56e3b9c2.png)

感谢感谢
