### ISSUE TITLE
按照教程添加了腾讯COS但是不能上传图片

### ISSUE THREAD

**Issue by ShengRui2021** [lsky-org/lsky-pro#348]
上传的时候提示 ：上传失败, 服务异常，请稍后再试
七牛云就没事 只有腾讯cos不能用

**Comment by wisp-x** [comment]
https://docs.lsky.pro/docs/v2/storage/faq.html#%E8%85%BE%E8%AE%AF%E4%BA%91-cos

**Comment by OriLight152** [comment]
换个地域的存储桶试试，我香港服务器不知道为什么往南京的存储桶上传会报错，换个地域就好了
