### ISSUE TITLE
在宝塔安装了 Fileinfo 拓展，但安装程序显示未安装

### ISSUE THREAD

**Issue by Kelejun** [lsky-org/lsky-pro#351]
如题。

![image](https://user-images.githubusercontent.com/63855342/159857527-bbe14360-97b7-4d61-afd2-e3b189238608.png)

![image](https://user-images.githubusercontent.com/63855342/159857437-9b94ca8d-e851-45cf-9404-63371200b661.png)

**Comment by wisp-x** [comment]
你应该去问宝塔官方。

**Comment by SAquarius** [comment]
重启PHP就可以了
