### ISSUE TITLE
邮箱验证出现403的问题

### ISSUE THREAD

**Issue by Cinnamoroll-cat** [lsky-org/lsky-pro#353]
如题，我在使用邮箱进行验证时，无意间发现了403错误，使用的版本是最新的2.0.2版本。而且并不是开启邮箱验证后账号无法登录除非进行验证那种，希望修复。

**Comment by wisp-x** [comment]
请详细说明场景
- 测试邮件发送时403？
- 找回密码、注册时403？
- 是 nginx 返回的403还是程序返回的 403 错误？

**Comment by Cinnamoroll-cat** [comment]
测试邮件发送时正常发送，注册时验证邮件点击链接出现的403错误，是程序返回的403错误界面。

**Comment by wisp-x** [comment]
未复现成功，测试正常。

**Comment by Cinnamoroll-cat** [comment]
![AC46BF48-21A4-4C0D-AE07-C1551C4FAA23](https://user-images.githubusercontent.com/61970096/159920633-a0d86846-67f2-442b-b28e-37cb8245f163.png)

**Comment by Cinnamoroll-cat** [comment]
这种问题我经常出现

**Comment by Cinnamoroll-cat** [comment]
你可以使用这个网址进行测试，如果不是真正程序的问题，那么可能是我安装或者数据库配置问题，我测试了，nginx报错并不是这样。https://pics.mojy.xyz/

**Comment by wisp-x** [comment]
是否有强制 https？`URL::forceScheme('https');`

**Comment by Cinnamoroll-cat** [comment]
> 是否有强制 https？`URL::forceScheme('https');`

是的

**Comment by wisp-x** [comment]
请参考：https://github.com/laravel/framework/issues/26930#issuecomment-559451441

**Comment by hiBenzhu** [comment]
这个具体是怎么解决呢 参考了好像还是不会弄哇

**Comment by wisp-x** [comment]
详见：https://github.com/lsky-org/lsky-pro/issues/374#issuecomment-1086928500
