### ISSUE TITLE
希望能支持github图片作为图床

### ISSUE THREAD

**Issue by Cinnamoroll-cat** [lsky-org/lsky-pro#354]
如题，希望可以使用github库作为图床使用。

**Comment by wisp-x** [comment]
https://docs.lsky.pro/docs/v2/#%E5%8F%8D%E9%A6%88%E9%97%AE%E9%A2%98

**Comment by Cinnamoroll-cat** [comment]
> https://docs.lsky.pro/docs/v2/#%E5%8F%8D%E9%A6%88%E9%97%AE%E9%A2%98

好的，看来使用github是够呛了。
