### ISSUE TITLE
手贱把数据库给删除了

### ISSUE THREAD

**Issue by only-matthew** [lsky-org/lsky-pro#358]
手贱把数据库给删除了，但是有备份，只是数据库密码丢失，请问数据库密码储存在哪里？

**Comment by HazukiKaguya** [comment]
数据库密码不是你创建时设置的吗？
意思是恢复了数据但是密码不同了吗？
看看.env，应该是在那里面？

**Comment by wisp-x** [comment]
在 `.env` 文件中。
