### ISSUE TITLE
关于api中token的建议

### ISSUE THREAD

**Issue by Gahotx** [lsky-org/lsky-pro#362]
1. 希望可以添加api查询已生成的token，和单独删除某条token
2. 现在通过api清空token，后面生成的token序号还是接着上次的，而不是重新由"1|xxx"开始
3. 像1.x版本中用户有一个默认的token还是挺方便的（对不熟悉http请求获取token的使用者来说）

**Comment by wisp-x** [comment]
本就不是给不熟悉的人使用的。
