### ISSUE TITLE
使用CDN 上传图片为什么会提示服务端错误 

### ISSUE THREAD

**Issue by dashen119** [lsky-org/lsky-pro#365]
使用CDN 上传图片为什么会提示服务端错误  

似乎是某个地方的限制导致CDN后无法通信 只能服务器源Ip才可以

**Comment by anghunk** [comment]
> 使用CDN 上传图片为什么会提示服务端错误
> 
> 似乎是某个地方的限制导致CDN后无法通信 只能服务器源Ip才可以

你好，我在测试的时候也遇到了类似的问题，请问您那边解决了吗？
![image](https://user-images.githubusercontent.com/65840178/160971124-caac3e8d-8b6a-429c-9e9e-7b814ab3bec1.png)

**Comment by wisp-x** [comment]
@anghunk 打开控制台看看 network，大概率是因为 https 站点请求了 http 的地址导致的。使用了 cdn，或反向代理，请在回源时使用 https，否则可能会导致程序识别成了 http 请求。

**Comment by anghunk** [comment]
> @anghunk 打开控制台看看 network，大概率是因为 https 站点请求了 http 的地址导致的。使用了 cdn，或反向代理，请在回源时使用 https，否则可能会导致程序识别成了 http 请求。

我在腾讯cos中没有开启cdn，请求的是默认的https://.............myqcloud.com 那个域名，console也没有报错，应该也不是系统的问题，我使用本地策略可以正常上传，腾讯云的设置我看了都正常，像是腾讯官方存储地域出问题了。等到下午或者明天我再试一下。

**Comment by wisp-x** [comment]
@anghunk 检查是不是配置错了，腾讯云的储存桶名称和appid需要分开填写。
https://docs.lsky.pro/docs/v2/storage/faq.html#%E8%85%BE%E8%AE%AF%E4%BA%91-cos

**Comment by anghunk** [comment]
> @anghunk 检查是不是配置错了，腾讯云的储存桶名称和appid需要分开填写。 https://docs.lsky.pro/docs/v2/storage/faq.html#%E8%85%BE%E8%AE%AF%E4%BA%91-cos

真的是这样，腾讯云里面储存桶名称我是imgbed-xxxxxxxxx，在网页填写配置要把appid去掉。没注意到这点，感谢提醒！
