### ISSUE TITLE
宝塔安装图床，生成连接还是http

### ISSUE THREAD

**Issue by GloamingCN** [lsky-org/lsky-pro#368]
宝塔安装的图床，域名已经是https了，但是生成的url还是http的，我按照https://laravel.com/docs/9.x/requests#configuring-trusted-proxies这个方法，修改了文件，但是没有什么作用

**Comment by zheyiyuezhuo** [comment]
我也差不多，可能反向代理没配置好

**Comment by wisp-x** [comment]
编辑 .env 文件，将里面的 url 改成 https 的试一下

**Comment by hellodk34** [comment]
@GloamingCN @zheyiyuezhuo 编辑一下存储策略，查看一下这里的 `访问网址` 链接是否是 https 的

![编辑一下存储策略.png](https://pic.dogimg.com/2022/04/01/62466b965fc36.png)

**Comment by GloamingCN** [comment]
> @GloamingCN @zheyiyuezhuo 编辑一下存储策略，查看一下这里的 `访问网址` 链接是否是 https 的
> 
> ![编辑一下存储策略.png](https://camo.githubusercontent.com/89c0cea76cbd31854d0e27c11f79d6226dfc7e51ba27b44f789c72f165f48fb9/68747470733a2f2f7069632e646f67696d672e636f6d2f323032322f30342f30312f363234363662393635666333362e706e67)

实际测试可行，感谢
