### ISSUE TITLE
升级改建建议

### ISSUE THREAD

**Issue by fcwys** [lsky-org/lsky-pro#371]
希望支持手动下载离线包到指定目录进行升级

**Comment by akatsukiro** [comment]
支持手动升级。
https://docs.lsky.pro/docs/v2/quick-start/upgrade.html#%E5%9C%A8%E7%BA%BF%E5%8D%87%E7%BA%A7

**Comment by wisp-x** [comment]
2.x 的升级方式已经不是解压压缩包了，而是通过接口遍历改变过的差异文件进行下载并覆盖。

**Comment by Gahotx** [comment]
在线升级报错了，请问是什么情况？权限我检查了都是755了
![F(97SQGWUKU2UQ 6EWJ_ 1M](https://user-images.githubusercontent.com/53534938/161368905-f271bced-5834-42c3-95a7-bfee13b8129c.png)
![QK1)CK8AR8A37 0T@BA}A4L](https://user-images.githubusercontent.com/53534938/161368908-b599a6d5-4748-4fd7-9b1b-73b01e4b2fd3.png)

**Comment by wisp-x** [comment]
> 在线升级报错了，请问是什么情况？权限我检查了都是755了
> 
> ![F(97SQGWUKU2UQ 6EWJ_ 1M](https://user-images.githubusercontent.com/53534938/161368905-f271bced-5834-42c3-95a7-bfee13b8129c.png)
> 
> ![QK1)CK8AR8A37 0T@BA}A4L](https://user-images.githubusercontent.com/53534938/161368908-b599a6d5-4748-4fd7-9b1b-73b01e4b2fd3.png)
> 
> 

在线更新失败就尝试手动升级
