### ISSUE TITLE
邮件验证链接返回403

### ISSUE THREAD

**Issue by hiBenzhu** [lsky-org/lsky-pro#374]
新用户注册后邮件验证链接点击进去 登陆之后直接返回403页面 是软件的403页面，前面问题参考了不会处理

麻烦给小白一点具体的修改思路或者方案，在此感激不尽，不然真的就要关了邮件验证选项了

**Comment by wisp-x** [comment]
是否按官方文档安装、是否有使用cdn、反向代理等等，说清楚。

**Comment by hiBenzhu** [comment]
> 是否按官方文档安装、是否有使用cdn、反向代理等等，说清楚。

今天刚用宝塔面板安装的 没有用cdn 反向代理啥的 自己注册了一个账号要邮件激活才发现的

**Comment by wisp-x** [comment]
尝试一下用php8在根目录执行 `php artisan key:generate` 看看能不能解决

**Comment by wisp-x** [comment]
看一下根目录`.env`文件的`APP_URL`的值是否和你设置的站点域名一致。

**Comment by hiBenzhu** [comment]
![Uploading 06F9449C-EFCB-407F-8A3A-4780EFB36F2D.jpeg…]()
好像报错了

**Comment by hiBenzhu** [comment]
![Uploading 195A3910-07FC-4EC9-84D6-13DCBF07D89D.jpeg…]()

**Comment by wisp-x** [comment]
@hiBenzhu 你图裂了

**Comment by hiBenzhu** [comment]
[![qH2AFU.jpg](https://s1.ax1x.com/2022/04/04/qH2AFU.jpg)](https://imgtu.com/i/qH2AFU)

**Comment by hiBenzhu** [comment]
env里边的appurl改成了我的域名了的

**Comment by wisp-x** [comment]
@hiBenzhu 在程序根目录执行，你这个是在哪个目录？

**Comment by hiBenzhu** [comment]
[![qH28YD.png](https://s1.ax1x.com/2022/04/04/qH28YD.png)](https://imgtu.com/i/qH28YD)
 以上命令都在程序根目录执行成功了 但还是这个样子

**Comment by wisp-x** [comment]
不知道什么原因，不介意就把宝塔账号密码以及站点名称发至邮箱 i@wispx.cn 吧，我这里无法重现。

**Comment by hiBenzhu** [comment]
已发

**Comment by wisp-x** [comment]
@hiBenzhu 经排查，系伪静态设置错误导致程序接收到了错误的签名，原伪静态：
```
location / {
    if (!-e $request_filename) {
    	rewrite ^(.*)$ /index.php?s=$1 last; break;
    }
}
```

而正确的伪静态应该是：

```
location / {
  try_files $uri $uri/ /index.php?$query_string;
}
```

文档地址：https://docs.lsky.pro/docs/v2/quick-start/installation.html#%E5%87%86%E5%A4%87%E5%AE%89%E8%A3%85

**Comment by hiBenzhu** [comment]
感谢麻烦这么久 原来是这个问题 我昨天根据官方文档安装的时候打开网站404，就去百度了别的博客安装教程 设置了他们给的伪静态，所以才变成这样了🫣 我居然把这茬忘了 实在麻烦

**Comment by wisp-x** [comment]
解决了就好，那就先关闭了，还有问题可以重新打开此 issue。

**Comment by hiBenzhu** [comment]
问题复现 今天凌晨解决好伪静态后我没有再次尝试 上午我试了一下还是原来的403错误

还是软件报的403

[![qbAlYq.png](https://s1.ax1x.com/2022/04/04/qbAlYq.png)](https://imgtu.com/i/qbAlYq)

**Comment by wisp-x** [comment]
自己再仔细检查一下吧，我试过没有问题。

**Comment by wisp-x** [comment]
@hiBenzhu 刚刚复现了，我在排查一下看看。

**Comment by wisp-x** [comment]
@hiBenzhu 找到原因了。访问激活链接时，你需要登录需要激活的账号，而不是其他账号，否则激活链接的签名和账号不匹配就会显示 403 无权限。

**Comment by hiBenzhu** [comment]
嗯嗯 已解决 感谢
