### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by lianyant** [lsky-org/lsky-pro#375]
当兰空图床创建了腾讯云 COS的存储策略后，往兰空图床中的腾讯云 COS的存储策略中上传图片、删除图片等等操作 是会在腾讯云的cos那边同步的。但是我发现同步是单向同步的，即会出现这些情况：(1)直接去腾讯云的cos那边上传图片，并不会在兰空图床这边同步更新出来这个单独在腾讯云cos上传的图片 (2)单独去腾讯云cos那边删除图片，也不会导致所删除的腾讯云cos中的图片所对应的兰空图床中的那个图片被删除掉 (3) 在腾讯云那边修改下图片的名称后，那么在兰空图床这边删除对应的图片后，也会导致删除不了对应的腾讯云cos这边的该修改了名称的图片了。。。。。。   也就是希望能够实现双向同步(即(1)(2)(3)步骤能够双向同步 )，我是小白，我只是希望这个功能能够实现，不要喷我(-.-)

**Comment by babiqqq** [comment]
牵扯到双向通信的问题了，这就不该是一个图床程序该考虑的问题了。如果双向同步功能实现了，其实也相当于给cos造了个前端（即网盘）。就像mysql主从一样，理应只保留一个端进行读写操作，这样效率更快。同时实现双向，更多的是程序需要大范围改动，图床主动拉取并比对文件的话也很消耗系统资源。

**Comment by wisp-x** [comment]
实现不了，因为部分储存没有提供删除/创建文件的回调功能，程序也不可能主动去同步文件，这个场景只有本地储存才最合适。

**Comment by lianyant** [comment]
> 

好的，明白了。多谢解答！
