### ISSUE TITLE
api 接口删除无论成功与否皆返回 200

### ISSUE THREAD

**Issue by heddxh** [lsky-org/lsky-pro#383]
最新版本2.0.3，Docker 安装
本地存储策略

使用接口删除一个不存在的文件，仍返回
```
{
  "status": true,
  "message": "删除成功",
  "data": {}
}
```

**Comment by wisp-x** [comment]
https://github.com/lsky-org/lsky-pro/issues/366#issuecomment-1082845068

**Comment by heddxh** [comment]
不是七牛云，是本地存储

**Comment by wisp-x** [comment]
> **程序删除操作永远都是返回成功的状态，目的是避免修改、删除了储存策略配置导致删除失败的问题。如果发现物理图片没有删除成功，正常情况下在程序 `storage/logs` 目录里可以找到详细的错误日志。**

**Comment by wisp-x** [comment]
就看第一行，其他的就不看了是吗

**Comment by heddxh** [comment]
抱歉，我以为下面那段专指七牛云
