### ISSUE TITLE
建议：整合一些三方教学中提供的必要信息

### ISSUE THREAD

**Issue by GoodManWEN** [lsky-org/lsky-pro#400]
很喜欢这个项目，但是由于我完全不了解php，依据文档配置过程中遇到很多问题，例如文档中要求php需要安装一系列扩展，而我并不了解其中哪些是php默认配置下自带的，哪些需要通过第三方安装。我上网搜索php扩展安装方式，依据其中说法到[pecl.php.net](pecl.php.net)中搜索，但文档中提供的第一个扩展在该服务中就无法查到，实在令人头大。

我觉得文档中既然提供了非开发人员配置的选项，那么可以考虑整合一些三方教学中必要的信息予以补充，比如插件安装大致流程。毕竟一般来说按照习惯都是参考文档进行quick start的，直觉上不会去搜索引擎搜索“教学”一类的东西，而我是在搜索引擎搜索后问题才得到解决，希望文档能适当进行补充。

**Comment by GoodManWEN** [comment]
Not an issue.

**Comment by A3597466** [comment]
对的，最好弄个docker。
