### ISSUE TITLE
python中添加header头无法上传

### ISSUE THREAD

**Issue by bpa6** [lsky-org/lsky-pro#403]
```
import requests

header = {
    "Content-Type": "multipart/form-data"
}

files = [
    ('file', open('tu.jpg', 'rb'))
]
url = 'https://url/api/v1/upload'
#a1 = requests.post(url=url, files=files, headers=header, verify=False)
a1 = requests.post(url=url, files=files, verify=False)
print(a1.text)
```

**Comment by wisp-x** [comment]
```python
import requests

headers = {
  'Content-Type": "multipart/form-data',
  'Accept': 'application/json',
  'x-requested-with': 'XMLHttpRequest',
}


```

**Comment by wisp-x** [comment]
前往文件夹 `storage/logs` 目录，里面有详细的错误日志。

**Comment by bpa6** [comment]
[laravel-2022-04-29.log](https://github.com/lsky-org/lsky-pro/files/8587914/laravel-2022-04-29.log)

**Comment by wisp-x** [comment]
看起来是没有获取到文件拓展名称，检查一下你这个文件上传的对不对吧，python 我不太懂。

**Comment by bpa6** [comment]
删除header头可以上传 
`{"status":true,"message":"\u4e0a\u4f20\u6210\u529f","data":{"key":"gm2pc5","name":"626ac1ac54129.jpg","pathname":"2022\/04\/29\/626ac1ac54129.jpg","origin_name":"no.jpg","size":5.095703125,"mimetype":"image\/jpeg","extension":"jpg","md5":"c080d2ec112dcd89c3f45e243381c6e3","sha1":"e1432b68297d3faed808ebac7007556596d9a3be","links":{"url":"https:\/\/test.com\/i\/2022\/04\/29\/626ac1ac54129.jpg","html":"&lt;img src=\"https:\/\/test.com\/i\/2022\/04\/29\/626ac1ac54129.jpg\" alt=\"no.jpg\" title=\"no.jpg\" \/&gt;","bbcode":"[img]https:\/\/test.com\/i\/2022\/04\/29\/626ac1ac54129.jpg[\/img]","markdown":"![no.jpg](https:\/\/test.com\/i\/2022\/04\/29\/626ac1ac54129.jpg)","markdown_with_link":"[![no.jpg](https:\/\/test.com\/i\/2022\/04\/29\/626ac1ac54129.jpg)](https:\/\/test.com\/i\/2022\/04\/29\/626ac1ac54129.jpg)","thumbnail_url":"https:\/\/test.com\/thumbnails\/c080d2ec112dcd89c3f45e243381c6e3.png"}}}`

**Comment by txuw** [comment]
```
import requests
headers = {
    # "Content-Type":"multipart/form-data",
    "Authorization":"xxx",
    "Accept":"application/json",
}


if __name__ == "__main__":
    path = 'F:/Music/ccc.png'
    data = {
    "file" :('file.jpg',open(path,'rb'),'image/png')
    }
    files = [
        ('file',open(path,'rb'))
    ]
    # print(headers)
    url = 'xxx'
    r = requests.post(url,files = data,headers=headers)
    r.encoding = "utf-8"
    print(r.json())
```

将content-type注释以后也可以，识别成form-data后无法正常读取，不太理解是为什么， @wisp-x ，是python的语法问题吗

**Comment by wisp-x** [comment]
@txuw 抱歉，我对 python 不是很了解。
