### ISSUE TITLE
非本地ftp(127.0.0.1)无法上传

### ISSUE THREAD

**Issue by ZZCYUN** [lsky-org/lsky-pro#408]
非本地ftp(127.0.0.1)无法正常上传，但是可以见到另一个服务器上生成了文件夹，但是文件却无法上传上去

**Comment by penndu** [comment]
是不是权限设置的问题？

**Comment by ZZCYUN** [comment]
使用其它的FTP管理器是可以上传文件的

**Comment by penndu** [comment]
问题解决了吗？

**Comment by coldquiet1** [comment]
> 问题解决了吗？

我也是这种问题
![KI)EA7MHYO31LRICA`I0`)5](https://user-images.githubusercontent.com/14888399/172011143-32786819-0426-413b-bbf4-c102f912aff2.png)

**Comment by wisp-x** [comment]
首先检查服务器防火墙，然后试一试切换主被动模式，详见此帖：https://stackoverflow.com/questions/44766158/php-connect-nonb-failed-operation-now-in-progress-115-with-tls-ssl-encryp
