### ISSUE TITLE
是否考虑添加上传图片自动转换格式的功能？（如自动转换WebP格式）

### ISSUE THREAD

**Issue by RalstonLiu** [lsky-org/lsky-pro#415]
作者您好！是否考虑在后台添加一个功能，可以让上传图片自动转换格式？比如可以设置成WebP，这样后台设置之后，可以自动将上传的图片转换为WebP格式，可以减少图片的体积，更加适合作为博客文章中的图片。

类似这种：

![](https://img.laoda.de/i/2022/05/06/sslkp0.webp)

**Comment by leealu** [comment]
我以为我没找到这个功能,原来是没有

**Comment by cye18** [comment]
+1，这个功能很实用啊

**Comment by covein** [comment]
> 作者您好！是否考虑在后台添加一个功能，可以让上传图片自动转换格式？比如可以设置成WebP，这样后台设置之后，可以自动将上传的图片转换为WebP格式，可以减少图片的体积，更加适合作为博客文章中的图片。
> 
> 类似这种：
> 
> ![](https://camo.githubusercontent.com/5b27864771e3ccef6917103ce23155a92a4532f05f9f808219ba3b3f0a343d04/68747470733a2f2f696d672e6c616f64612e64652f692f323032322f30352f30362f73736c6b70302e77656270)

你这个图片中的是什么图床啊

**Comment by RalstonLiu** [comment]
> > 作者您好！是否考虑在后台添加一个功能，可以让上传图片自动转换格式？比如可以设置成WebP，这样后台设置之后，可以自动将上传的图片转换为WebP格式，可以减少图片的体积，更加适合作为博客文章中的图片。
> > 类似这种：
> > ![](https://camo.githubusercontent.com/5b27864771e3ccef6917103ce23155a92a4532f05f9f808219ba3b3f0a343d04/68747470733a2f2f696d672e6c616f64612e64652f692f323032322f30352f30362f73736c6b70302e77656270)
> 
> 你这个图片中的是什么图床啊

easyimages   https://blog.laoda.de/archives/docker-compose-install-easyimage
