### ISSUE TITLE
求助：首次安装，install界面无法正常载入

### ISSUE THREAD

**Issue by ZhangXQA** [lsky-org/lsky-pro#425]
有没有人遇见过这种情况啊，求助一下各位。
首次安装兰空，环境：MySQL5.7,PHP8.1,Nginx1.2.
很仔细地按照文档做了各个步骤，甚至因为不成功重新来了好几遍。PHP扩展和函数也都按官方的要求做好了。
下载的是非Source code版本，下了v2.0.4和v2.0都试过了
首次安装的页面是这样的
[![O7ROHA.md.png](https://s1.ax1x.com/2022/05/19/O7ROHA.md.png)](https://imgtu.com/i/O7ROHA)
[![O7RjAI.md.png](https://s1.ax1x.com/2022/05/19/O7RjAI.md.png)](https://imgtu.com/i/O7RjAI)

不知道问题出在哪儿啊，像这样正常填数据点下一步的话没有任何反应。

**Comment by wisp-x** [comment]
![image](https://user-images.githubusercontent.com/22728201/169167755-65bfe222-eac4-4425-8700-d7c775120ddd.png)

**Comment by ZhangXQA** [comment]
> 不好意思，方便能说下问题出在哪儿吗，防跨站我关了的呀？

**Comment by ZhangXQA** [comment]
可能是我服务器的问题，不好意思，感谢帮助
