### ISSUE TITLE
v2.0.4 接口上传图片一直失败，返回Call to a member function getClientOriginalExtension() on null

### ISSUE THREAD

**Issue by xiaobai1226** [lsky-org/lsky-pro#427]
版本：V 2.0.4
通过图形化上传图片是没问题的，但配置picgo时一直上传失败，然后我尝试用接口上传图片也一直失败
状态码是200 ok，但响应体内容为：
{
"status": false,
"message": "Call to a member function getClientOriginalExtension() on null",
"data":{}
}

**Comment by penndu** [comment]
https://dusays.com/455/
教程参考一下！

**Comment by xiaobai1226** [comment]
> https://dusays.com/455/ 教程参考一下！

我试过了，都不行

**Comment by wisp-x** [comment]
程序没有获取到上传文件的拓展名称导致的，检查你上传的文件。

**Comment by xiaobai1226** [comment]
问题解决了
1、自己用接口上传失败原因是用的http工具有问题，他会自动修改请求头里的信息，换了postman就正常了
2、picgo失败是因为插件问题应该是证书过期了，我忽略了证书错误就没问题了

**Comment by z1zhang** [comment]
感谢，解决了
