### ISSUE TITLE
使用nginx配置Content-Security-Policy策略后，无法弹出登录界面

### ISSUE THREAD

**Issue by xhpk** [lsky-org/lsky-pro#436]
nginx中配置了一条策略
“ add_header Content-Security-Policy   "default-src 'self' http: https: ws: wss: data: blob: 'unsafe-inline'; frame-ancestors 'self';" always;”
之后，打开网站显示以下界面
![image](https://user-images.githubusercontent.com/40262993/170493359-61b80027-b8d1-404f-8266-b81e7d04fb58.png)

F12调试显示
![image](https://user-images.githubusercontent.com/40262993/170493584-87e041c7-5f7f-4a97-87b6-aa15a0948792.png)
![image](https://user-images.githubusercontent.com/40262993/170495167-e7f5d06d-1d4e-49f3-988c-287f5053d786.png)

文字版
```
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "default-src 'self' http: https: ws: wss: data: blob: 'unsafe-inline'".

    at new AsyncFunction (<anonymous>)
    at app.js?t=20220427:2:21565
    at app.js?t=20220427:2:21723
    at app.js?t=20220427:2:21742
    at X (app.js?t=20220427:2:22035)
    at U (app.js?t=20220427:2:21143)
    at Function.<anonymous> (app.js?t=20220427:2:50195)
    at n (app.js?t=20220427:2:25142)
    at app.js?t=20220427:2:25170
    at je (app.js?t=20220427:2:25174)
```

**Comment by wisp-x** [comment]
这是浏览器的安全策略限制。https://developer.chrome.com/docs/apps/contentSecurityPolicy

**Comment by xhpk** [comment]
> 这是浏览器的安全策略限制。https://developer.chrome.com/docs/apps/contentSecurityPolicy

是的，因为这个策略我同样用在其它网站上了，但是只有图床出现这个问题。

**Comment by wisp-x** [comment]
因为兰空图床使用了 aloinejs，我也没有详细的了解，你可以看看这个：https://github.com/alpinejs/alpine/issues/63

**Comment by xhpk** [comment]
> 因为兰空图床使用了 aloinejs，我也没有详细的了解，你可以看看这个：[alpinejs/alpine#63](https://github.com/alpinejs/alpine/issues/63)

ok，多谢，明白了，已经搞定了！
