### ISSUE TITLE
初始安装报错

### ISSUE THREAD

**Issue by QQ853695231** [lsky-org/lsky-pro#438]
![IMG_20220529_221043.jpg](https://user-images.githubusercontent.com/22435948/170873484-b12b3aa2-f247-4459-acab-e77cefb17516.jpg)在安装界面，会报错。

**Comment by penndu** [comment]
mysql的版本？

**Comment by QQ853695231** [comment]
5.7.8rc

**Comment by wisp-x** [comment]
![image](https://user-images.githubusercontent.com/22728201/170874771-9ace4ab0-2015-4a7d-ba09-8fb22a0b2644.png)
按照图中步骤操作。
