### ISSUE TITLE
腾讯云COS 查看图片时404

### ISSUE THREAD

**Issue by FunnySaltyFish** [lsky-org/lsky-pro#450]
使用腾讯云COS，目前情况是：
- 上传成功
- 主页可以预览缩约图，但无法查看大图
  ![image](https://user-images.githubusercontent.com/46063434/174447010-7b590b44-39b5-406b-ba13-84107aa1a3b0.png)

 - 腾讯云 cos 正确创建资源（共有读私有写，无防盗链）
- 访问图片链接 404
![image](https://user-images.githubusercontent.com/46063434/174447039-3f955c30-94ab-4354-a6e7-6b027ab75e61.png)

**Comment by penndu** [comment]
这个cos是什么情况？
![image](https://user-images.githubusercontent.com/46226528/174447526-5a90eb86-0db5-44e5-bdfe-b7a463755568.png)

**Comment by FunnySaltyFish** [comment]
cos 是我存储策略时定义的url。不过也不必了，我才发现原来COS流量和调用是额外收费的，放弃了
