### ISSUE TITLE
页面默认是ip，怎么设置成域名呢

### ISSUE THREAD

**Issue by zhang-zzq** [lsky-org/lsky-pro#454]
域名访问，点击登录，跳转的地址是ip的地址、接口地址也是ip的地址，请问怎么设置成域名呢

**Comment by wisp-x** [comment]
为什么会跳转到 IP，请详细说明。

**Comment by zhang-zzq** [comment]
通过域名访问，点击登录的时候跳转到ip+端口的页面了。接口的地址也是ip+端口的，可以修改这个默认地址吗

**Comment by penndu** [comment]
> 通过域名访问，点击登录的时候跳转到ip+端口的页面了。接口的地址也是ip+端口的，可以修改这个默认地址吗

服务器是什么系统？
是如何部署的？
用什么浏览器？
域名多少？

**Comment by zhang-zzq** [comment]
centos
docker部署
谷歌浏览器
img.zzq.plus

**Comment by penndu** [comment]
lsky-pro没有域名绑定的设置，也就是说没有默认地址。

去看了下，确实有ip+端口问题，你用什么做的反代？

**Comment by zhang-zzq** [comment]
nginx

**Comment by zhang-zzq** [comment]
正常是怎么实现域名访问呢

**Comment by penndu** [comment]
> 正常是怎么实现域名访问呢

nginx反代配好后，使用域名直接安装。

而不是通过IP和端口来安装！

**Comment by zhang-zzq** [comment]
域名安装的时候点击安装没有反应

**Comment by penndu** [comment]
> 域名安装的时候点击安装没有反应

![image](https://user-images.githubusercontent.com/46226528/174942251-e53afda3-68d3-45b1-8747-ddac80234576.png)
修改此处试试。

**Comment by zhang-zzq** [comment]
好的，感谢

**Comment by wisp-x** [comment]
把你的反代配置文件发出来看一下

**Comment by zhang-zzq** [comment]
> 把你的反代配置文件发出来看

> 把你的反代配置文件发出来看一下

server {
    listen       80;
    server_name  img.zzq.plus;

    charset utf-8;

    location / {
       proxy_pass http://49.232.17.43:7791;
    }

}

**Comment by penndu** [comment]
供参考
```
#PROXY-START/
location /
{
    proxy_pass http://127.0.0.1:8080;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header REMOTE-HOST $remote_addr;
    
    add_header X-Cache $upstream_cache_status;
    add_header Access-Control-Allow-Origin "" always;
    
    #Set Nginx Cache
    
    	add_header Cache-Control no-cache;
    expires 12h;
}

#PROXY-END/
```

**Comment by zhang-zzq** [comment]
> 供参考
> 
> ```
> #PROXY-START/
> location /
> {
>     proxy_pass http://127.0.0.1:8080;
>     proxy_set_header Host $host;
>     proxy_set_header X-Real-IP $remote_addr;
>     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>     proxy_set_header REMOTE-HOST $remote_addr;
>     
>     add_header X-Cache $upstream_cache_status;
>     add_header Access-Control-Allow-Origin "" always;
>     
>     #Set Nginx Cache
>     
>     	add_header Cache-Control no-cache;
>     expires 12h;
> }
> 
> #PROXY-END/
> ```

这个可以了，在域名页面安装的。感谢感谢

**Comment by xhmotor** [comment]
> 供参考
> 
> ```
> #PROXY-START/
> location /
> {
>     proxy_pass http://127.0.0.1:8080;
>     proxy_set_header Host $host;
>     proxy_set_header X-Real-IP $remote_addr;
>     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>     proxy_set_header REMOTE-HOST $remote_addr;
>     
>     add_header X-Cache $upstream_cache_status;
>     add_header Access-Control-Allow-Origin "" always;
>     
>     #Set Nginx Cache
>     
>     	add_header Cache-Control no-cache;
>     expires 12h;
> }
> 
> #PROXY-END/
> ```

@zhang-zzq @penndu 请教下这个要在哪里修改?我也是安装后用nginx反代;返回到源域名;想试试用这个方法;但是新手不知在哪里修改
