### ISSUE TITLE
【BUG】升级后修改密码提示粘贴动作值选择错误

### ISSUE THREAD

**Issue by HazukiKaguya** [lsky-org/lsky-pro#455]
从2.0.1手动升级到2.0.4后，个人设置页面（/settings）修改密码时提示粘贴动作值选择错误
测试发现手动升级和自动升级都会如此，全新安装没这个问题，全新安装后恢复之前的数据库也会导致这个问题。

环境
CentOS 7.9.2009 x86_64
Nginx 1.20.2
PHP 8.0.17
Redis 6.2.6（php使用redis扩展）

**Comment by wisp-x** [comment]
设置页面中勾选选项【图片粘贴后动作】任意一项保存即可。

**Comment by HazukiKaguya** [comment]
> 设置页面中勾选选项【图片粘贴后动作】任意一项保存即可。

感谢，已解决，看起来是因为新版增加了一个之前没有的选项导致的，是否可以让旧版升级上来的用户在这个设置页面时默认选择等待上传（或者将这个弹出文案更改为”未设置必选项【图片粘贴后动作】，请设置好后再点击保存“）以避免这个问题？

**Comment by wisp-x** [comment]
> > 设置页面中勾选选项【图片粘贴后动作】任意一项保存即可。
> 
> 感谢，已解决，看起来是因为新版增加了一个之前没有的选项导致的，是否可以让旧版升级上来的用户在这个设置页面时默认选择等待上传（或者将这个弹出文案更改为”未设置必选项【图片粘贴后动作】，请设置好后再点击保存“）以避免这个问题？

这个版本已经发布了很久了，不会更改，后续版本更新的时候会给默认选项的。
