### ISSUE TITLE
安装完毕后，无法访问首页

### ISSUE THREAD

**Issue by flmelody** [lsky-org/lsky-pro#456]
Docker部署的Nginx反代；安装过程没有出错，数据库也生成了数据，点击返回首页，直接HTTP 500,兰空容器也只打印了一行日志

![Screenshot from 2022-06-24 08-39-27](https://user-images.githubusercontent.com/47545727/175437924-f49493ba-8048-495f-8b13-3db5dd25e199.png)
错误有点摸不着头脑

**Comment by penndu** [comment]
nginx反代规则发一下！

**Comment by wisp-x** [comment]
去程序的 `storage/logs` 目录看看有没有错误日志，贴出来。

**Comment by flmelody** [comment]
不能访问数据库，日志显示访问的是兰空容器自己的ip。。
![Screenshot from 2022-06-24 19-57-25](https://user-images.githubusercontent.com/47545727/175530076-eb226313-be9c-480f-a219-a9c275cc461d.png)
容器启动有这个警告，没有在意
![Screenshot from 2022-06-24 19-58-53](https://user-images.githubusercontent.com/47545727/175530268-6f507510-d4eb-4ff8-a3a3-c7bc1c909c31.png)
安装却没有问题，使用docker compose 同时拉起了数据库，是需要设置其它环境变量吗

**Comment by flmelody** [comment]
docker compose文件如下
![Screenshot from 2022-06-24 20-09-45](https://user-images.githubusercontent.com/47545727/175531414-b2623e91-a640-4112-b545-59988d5bcf5b.png)

**Comment by flmelody** [comment]
破案了，鄙人密码都喜欢加特殊字符，这里我给mysql密码加了个#，结果安装向导结束后无法访问首页，#符号特殊处理了？？
