### ISSUE TITLE
关于忘记密码功能：使用电子邮件地址发送重置密码邮件时文案的建议

### ISSUE THREAD

**Issue by hellodk34** [lsky-org/lsky-pro#460]
为了安全考虑，我觉得不应该向用户展示该邮箱是否有在我们的系统中注册。

![20220628211229](https://image.940304.xyz/i/2022/06/28/62bafe3e2356c.png)

如上图，如果输入一个数据库中不存在的 email，当前 Lsky Pro 会提醒用户该邮箱没有在我们的系统中注册，但是这样好像会带来一个隐式的问题，恍惚间就告诉了用户那个 email 没有在这个系统中注册？

我觉得可以优化成以下类似的文案：

**如果你输入的邮件地址在我们的数据库中存在，你应该能收到我们发送的重置密码的邮件，请尽快检查。**

似乎只需要改文案，不需要动判断邮箱是否在数据库中、发送邮件等业务逻辑。

**Comment by wisp-x** [comment]
你可以通过修改这个基础语言包文件来更换其他的提示文字。
https://github.com/lsky-org/lsky-pro/blob/2c52c87c95eb3842df5cfa971c326a791b12ed58/lang/zh_CN/passwords.php?_pjax=%23js-repo-pjax-container#L19

**Comment by wisp-x** [comment]
> lsky-pro/lang/zh_CN/passwords.php

可以改，不过这提示没什么问题吧。。
https://github.com/lsky-org/lsky-pro/blob/2c52c87c95eb3842df5cfa971c326a791b12ed58/lang/zh_CN.json#L686
https://github.com/lsky-org/lsky-pro/blob/2c52c87c95eb3842df5cfa971c326a791b12ed58/lang/zh_CN/zh_CN.json#L686

**Comment by hellodk34** [comment]
@wisp-x 其实论数据的敏感性，个人感觉是不应该直接这样“显示”告诉用户他输入的邮箱是否存在于我们的数据库中的。我之前的实践是不论用户输入什么邮箱，只要过了基础的邮箱 regex 验证，就提示他如果邮箱存在就能收到重置密码的邮件，这样用户就不能通过“反查”知道哪些邮箱哪些邮箱不存在了。如果是 pornhub 这种敏感网站，可以直接查暧昧对象的邮箱是否有注册 pornhub？当然我只是建议，这些对于图床的主要业务无关痛痒。
