### ISSUE TITLE
存储 策略问题

### ISSUE THREAD

**Issue by flmelody** [lsky-org/lsky-pro#461]
如何确定新建的存储策略生效了，并且可用呢，我这边加了腾讯云COS，用户组绑定这个策略后，会看不到这个存储，无法上传图片
![Screenshot from 2022-06-28 21-37-07](https://user-images.githubusercontent.com/47545727/176192661-5951ef95-ebf6-4a89-82fa-f2524c1ae2b5.png)
这个标签直接就没了。。

**Comment by design-1996** [comment]
BUG,这图床一直没修复这bug。基本上已经废了，能不能添加好 全看运气

**Comment by Jack-Ywn** [comment]
没有个启用选项，是为什么失败也不知道
