### ISSUE TITLE
缩略图可以存到外部去吗

### ISSUE THREAD

**Issue by moe-ms** [lsky-org/lsky-pro#463]
图片多了我发现缩略图也很占用空间
可以将缩略图也存到外部去吗

**Comment by tuchuang-ml** [comment]
另外缩略图似乎都存在同一个文件夹内。对于几百万张图片的大站来说，一个文件夹内几百万张图片显然会出现问题。希望后续能优化这个问题呀

**Comment by wisp-x** [comment]
不可以。一般第三方储存或 cdn 本身就具有图片处理规则来实现缩略图功能，并且放在外部储存还不便于管理，比如现在兰空图床可以自行删除所有缩略图(删除`public/thumbnails`目录所有文件即可)，如果需要重写生成只需要执行 `php artisan lsky:thumbnails` 就可以了。

**Comment by tuchuang-ml** [comment]
明白了。有2点建议写给开发者呀
1，游客与注册用户的缩略图分开存储，这样就可以定期删除游客的缩略图啦。
——
或者缩略图可以自动生成，例如说我已经定期删除了所有的缩略图，当注册用户登录查看自己的图片时，它可以自动生成。这样也会节省空间

2，缩略图还是根据日期创建子文件夹比较好。因为后续一个文件夹内文件过多会出现问题。

感谢这么好的开源图床

**Comment by wisp-x** [comment]
感谢支持，付费版本还在开发，还需要一阵子。取消缩略图需要修改代码：
https://github.com/lsky-org/lsky-pro/blob/2c52c87c95eb3842df5cfa971c326a791b12ed58/app/Services/ImageService.php#L253 注释掉这一行即可。

不过要注意的是，没有缩略图的话，如果图片尺寸过大，在列表页面展示时可能会有卡顿现象，并且消耗的流量更多。

**Comment by akatsukiro** [comment]
卡到怀疑人生，生活不能自理，即使你的电脑配置顶级，照样卡爆。不要问我怎么知道的。

**Comment by tuchuang-ml** [comment]
> 感谢支持，付费版本还在开发，还需要一阵子。取消缩略图需要修改代码：
> 
> https://github.com/lsky-org/lsky-pro/blob/2c52c87c95eb3842df5cfa971c326a791b12ed58/app/Services/ImageService.php#L253
> 
> 注释掉这一行即可。
> 不过要注意的是，没有缩略图的话，如果图片尺寸过大，在列表页面展示时可能会有卡顿现象，并且消耗的流量更多。

感谢指导，感谢，期待！
