### ISSUE TITLE
文件名导致前端图片显示炸了

### ISSUE THREAD

**Issue by znc15** [lsky-org/lsky-pro#471]
服务器是Centos7
电脑是Windows10
  
主要情况为：
当上传文件名为 ”CI$6M22$`]A7]E_JF$VB$OT.jpg”的时候，会导致前端图片显示炸了
  
炸掉后的图：
![TOH42 0LHG3 SO48~X($D}T](https://user-images.githubusercontent.com/64775575/178128665-0c781ce8-6117-40d0-b6ba-725fcacd7d1c.png)

网站已经开启了上传重命名，然后在图片管理没问题，只有我的图片会炸

**Comment by wisp-x** [comment]
方便的话可以发一下原图吗，复现不了。

**Comment by znc15** [comment]
> 方便的话可以发一下原图吗，复现不了。

https://www.miaofile.com/s/krec2
