### ISSUE TITLE
请问如何删除token

### ISSUE THREAD

**Issue by GC-ZF** [lsky-org/lsky-pro#475]
![image](https://user-images.githubusercontent.com/94956933/178693547-c47ded7d-0e54-4d31-830d-e62f244f08d7.png)

![image](https://user-images.githubusercontent.com/94956933/178693624-e86cea2d-bed7-4a6f-9e66-8b905724bdaf.png)

**Comment by penndu** [comment]
仅供参考https://dusays.com/454/

**Comment by GC-ZF** [comment]
> 仅供参考https://dusays.com/454/

无效
![image](https://user-images.githubusercontent.com/94956933/178702158-f3033bd1-6cc7-4870-b86f-7e83dc8dc6bd.png)

**Comment by GC-ZF** [comment]
已删除
