### ISSUE TITLE
关于nsfw-api鉴黄设置问题

### ISSUE THREAD

**Issue by itwhs** [lsky-org/lsky-pro#476]
您好
 
使用docker运行的lsky-pro.
后台环境变量
```bash
root@cdb640d7fcb0:/var/www/html# env
HOSTNAME=cdb640d7fcb0
PHP_VERSION=8.1.8
APACHE_CONFDIR=/etc/apache2
PHP_INI_DIR=/usr/local/etc/php
GPG_KEYS=528995BFEDFBA7191D46839EF9BA0ADA31CBD89E 39B641343D8C104B2B146DC3F9C39DC0B9698544 F1F692238FBC1666E5A5CCD4199F9DFEF6FFBAFD
PHP_LDFLAGS=-Wl,-O1 -pie
PWD=/var/www/html
HOME=/root
ASSET_URL='https://****************'
PHP_SHA256=04c065515bc347bc68e0bb1ac7182669a98a731e4a17727e5731650ad3d8de4c
PHPIZE_DEPS=autoconf            dpkg-dev                file            g++             gcc             libc-dev                make            pkg-config                re2c
TERM=xterm
PHP_URL=https://www.php.net/distributions/php-8.1.8.tar.xz
intercept_salacity=true
SHLVL=1
PHP_CFLAGS=-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
APACHE_ENVVARS=/etc/apache2/envvars
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PHP_ASC_URL=https://www.php.net/distributions/php-8.1.8.tar.xz.asc
PHP_CPPFLAGS=-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
_=/usr/bin/env
root@cdb640d7fcb0:/var/www/html# cat /var/www/html/.env
APP_NAME="Lsky Pro"
APP_ENV=prod
APP_KEY=base64:N2IQrYL85FNAuTRs1bQrdqWppfemlicxuh9cLBVxwaU=
APP_DEBUG=false
APP_URL=http://localhost

LOG_CHANNEL=daily
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=debug

DB_CONNECTION=sqlite
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=/var/www/html/database/database.sqlite
DB_USERNAME=root
DB_PASSWORD=root

BROADCAST_DRIVER=log
CACHE_DRIVER=file
FILESYSTEM_DISK=public
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120

MEMCACHED_HOST=127.0.0.1

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

IGNITION_SHARING_ENABLED=false
root@cdb640d7fcb0:/var/www/html#

```
![image](https://user-images.githubusercontent.com/42338078/178976472-596c3d55-6c76-4b0c-91ea-eddd48f98206.png)
网页端设置.

不可描述的照片仍然可以上传,而且也不删除,也不标记不健康.
![image](https://user-images.githubusercontent.com/42338078/178977060-d662a6cd-3711-4340-9c21-0f80ac275de5.png)

图片信息:
![image](https://user-images.githubusercontent.com/42338078/178977849-d236a4da-23a0-49e4-8baf-117034ae72cb.png)

请问是哪里配置错误了吗?试过很多方法,都能成功上传

有空的时候帮忙解惑.谢谢大佬

**Comment by penndu** [comment]
你自建的审核接口地址
你需要使用 node 环境启动一个服务器，并适配 nsfwjs。然后上传接口必须返回以下结构：
```
{
    "porn": 0,
    "sexy": 0,
    "hentai": 0,
    "neutral": 0,
    "drawing": 0
}
```

**Comment by itwhs** [comment]
> 
谢谢解答,有docker镜像名称吗?我想全部写到一个docker-compose里面启动

**Comment by penndu** [comment]
> > 
> 
> 谢谢解答,有docker镜像名称吗?我想全部写到一个docker-compose里面启动

这个好像没有，我用的是别人搭的~

**Comment by itwhs** [comment]
使用这个作者仓库的鉴黄API可以对接lsky图床,而且好像一直还在维护中.
https://github.com/arnidan/nsfw-api
问题已解决,效果:
![image](https://user-images.githubusercontent.com/42338078/179056986-ee1a0400-4257-4676-9e4c-50545c4e4f6e.png)

解决步骤:
1,如果网络环境好,本身就是国外机器做鉴黄使用.可以直接按照上面官方办法使用.
2,我主要使用的是全部部署在本地,而且镜像是在ghcr.io,国内没有加速,十分不友好,所以只能魔法打败魔法
a,使用github的action,把原作者镜像上传到dockerhub,然后国内下载(dockerhub国内加速较多)
![image](https://user-images.githubusercontent.com/42338078/179059050-ed551032-55d0-45b7-a381-7a3d9bd596b7.png)
b,使用阿里云的容器镜像服务(个人版有三个命名空间,300个容器),其实一个命名空间就完全够用,毕竟最后一个tag不一样,可以区分就够了(懂得都懂,前面名字虽然固定,但是最后一个tag字段有无限个版本,可以把仓库当中转站使用,实测下载可达300M+速度)
![image](https://user-images.githubusercontent.com/42338078/179060183-f0f8b75a-854b-4db4-a27d-12419225c452.png)

上面任意一个镜像,下载好后
```bash
docker run -itd  --name=nsfw-api --restart=unless-stopped -p 3000:3000 qingjiubaba/ghcr.io.arnidan.nsfw-api:latest
```
然后就是去后台设置鉴黄参数(我做了https的反向代理,反正都是局域网,可以不像我这样多此一举)
![image](https://user-images.githubusercontent.com/42338078/179061650-3105b29f-ac42-44ec-a053-74d8d501e655.png)

**Comment by itwhs** [comment]
遇到一个新问题,怎么才能查看到上传图片被鉴黄api分析图片的返回值是多少呢?如果知道返回值是多少,更容易调试百分比设置,来自动鉴黄.如果谁懂的话,麻烦放个截屏或者链接看看.

**Comment by huluohu** [comment]
> 使用这个作者仓库的鉴黄API可以对接lsky图床,而且好像一直还在维护中. https://github.com/arnidan/nsfw-api 问题已解决,效果: ![image](https://user-images.githubusercontent.com/42338078/179056986-ee1a0400-4257-4676-9e4c-50545c4e4f6e.png)
> 
> 解决步骤: 1,如果网络环境好,本身就是国外机器做鉴黄使用.可以直接按照上面官方办法使用. 2,我主要使用的是全部部署在本地,而且镜像是在ghcr.io,国内没有加速,十分不友好,所以只能魔法打败魔法 a,使用github的action,把原作者镜像上传到dockerhub,然后国内下载(dockerhub国内加速较多) ![image](https://user-images.githubusercontent.com/42338078/179059050-ed551032-55d0-45b7-a381-7a3d9bd596b7.png) b,使用阿里云的容器镜像服务(个人版有三个命名空间,300个容器),其实一个命名空间就完全够用,毕竟最后一个tag不一样,可以区分就够了(懂得都懂,前面名字虽然固定,但是最后一个tag字段有无限个版本,可以把仓库当中转站使用,实测下载可达300M+速度) ![image](https://user-images.githubusercontent.com/42338078/179060183-f0f8b75a-854b-4db4-a27d-12419225c452.png)
> 
> 上面任意一个镜像,下载好后
> 
> ```shell
> docker run -itd  --name=nsfw-api --restart=unless-stopped -p 3000:3000 qingjiubaba/ghcr.io.arnidan.nsfw-api:latest
> ```
> 
> 然后就是去后台设置鉴黄参数(我做了https的反向代理,反正都是局域网,可以不像我这样多此一举) ![image](https://user-images.githubusercontent.com/42338078/179061650-3105b29f-ac42-44ec-a053-74d8d501e655.png)

你好，首先感谢你的教程，成功搭建。

但是遇到一个问题，就是打开审核开关后，上传图片就会报失败，但是实际是上传了的。我在lsky容器里试了可以正常访问到nsfw。不知道哪地方除了问题。
