### ISSUE TITLE
博客照片无法展示

### ISSUE THREAD

**Issue by GC-ZF** [lsky-org/lsky-pro#477]
博客：Hexo
主题：Butterfly
Lsky-pro：未开启https
Picgo配置：
![image](https://user-images.githubusercontent.com/94956933/178991919-4f3e6bf3-28e5-4455-a79c-1e2c13263e81.png)
存储策略：
![image](https://user-images.githubusercontent.com/94956933/178992059-3509cdfc-ea9d-4ef5-9f0a-3ad690466822.png)
路径规则：
![image](https://user-images.githubusercontent.com/94956933/178995138-1941056c-9981-4f5c-a63d-de00aa39d5e4.png)

问题：无论我用Picgo上传还是从Lsky面板直接上传，本地md文件正常显示图片，本地部署预览(localhost:8088访问)也正常显示，一旦上传服务器(域名访问)，打开就不行了，而且手机端和ipad端正常，唯独电脑端
![image](https://user-images.githubusercontent.com/94956933/178993380-acaf1115-4aab-4176-b369-ff09754a89a0.png)
而且如果右击图片可以正常显示
![image](https://user-images.githubusercontent.com/94956933/178993663-c5821e0e-b556-4546-9d2c-8f88fa1ff3b5.png)
请问是哪里配置不对么？
博客地址zhangshier.vip

**Comment by penndu** [comment]
暂目测token有问题，可参考https://dusays.com/455/

**Comment by GC-ZF** [comment]
> 暂目测token有问题，可参考https://dusays.com/455/

我图片都能正常上传怎么可能是token问题

**Comment by penndu** [comment]
> > 暂目测token有问题，可参考https://dusays.com/455/
> 
> 我图片都能正常上传怎么可能是token问题

打码了看不起，留个联系方式，远程调试一下！

**Comment by GC-ZF** [comment]
试了一下和主题没关系，不知道是Hexo框架有问题还是Lsky，可是Hexo用了好久了，第一次遇见这样

**Comment by GC-ZF** [comment]
试了一下和主题没关系，不知道是Hexo框架有问题还是Lsky，可是Hexo用了好久了，第一次遇见这样

> > > 暂目测token有问题，可参考https://dusays.com/455/
> > 
> > 
> > 我图片都能正常上传怎么可能是token问题
> 
> 打码了看不起，留个联系方式，远程调试一下！

你vx？

**Comment by wisp-x** [comment]
![image](https://user-images.githubusercontent.com/22728201/179007619-a4d2e7cc-3a59-496c-bd08-ba544705ecd3.png)
![image](https://user-images.githubusercontent.com/22728201/179007501-fb9caa7f-95f4-495e-ae4a-751d9c4ed84f.png)

ssl证书问题。

**Comment by GC-ZF** [comment]
> ![image](https://user-images.githubusercontent.com/22728201/179007619-a4d2e7cc-3a59-496c-bd08-ba544705ecd3.png) ![image](https://user-images.githubusercontent.com/22728201/179007501-fb9caa7f-95f4-495e-ae4a-751d9c4ed84f.png)
> 
> ssl证书问题。

嗯，谢谢，我刚才也发现了，现在部署上ssl就好了，所以ssl是必须有么？我感觉好像是因为标头(一级域名)配了ssl，然后二级跳转的时候不能用证书，和兰空以及hexo没关系

**Comment by GC-ZF** [comment]
另外还想问一下，就是只能借助第三方设置域名白名单(图片防盗)？本地存储策略不支持对么？
