### ISSUE TITLE
图片链接无效

### ISSUE THREAD

**Issue by quinhua** [lsky-org/lsky-pro#483]
开启原图保护添加水印后图片链接无效-404

**Comment by wisp-x** [comment]
https://docs.lsky.pro/docs/v2/quick-start/questions.html#%E5%BC%80%E5%90%AF%E5%8E%9F%E5%9B%BE%E4%BF%9D%E6%8A%A4%E5%8A%9F%E8%83%BD%E5%90%8E%E8%AE%BF%E9%97%AE%E5%9B%BE%E7%89%87-404
