### ISSUE TITLE
部署此项目到服务器后访问返回500

### ISSUE THREAD

**Issue by Jerry12228** [lsky-org/lsky-pro#484]
部署此项目到服务器后访问返回500
尝试版本2.0、2.0.4
目录已绑public

**Comment by akatsukiro** [comment]
storage/logs/

**Comment by Jerry12228** [comment]
> production.ERROR: file_put_contents(/home/wwwroot/lnmp02/domain/lsky.jerrybest.tk/web/.env): Failed to open stream: Permission denied {"exception":"[object] (ErrorException(code: 0): file_put_contents(/home/wwwroot/lnmp02/domain/lsky.jerrybest.tk/web/.env): Failed to open stream: Permission denied at /home/wwwroot/lnmp02/domain/lsky.jerrybest.tk/web/app/Providers/AppServiceProvider.php:35)
谢谢您

**Comment by wisp-x** [comment]
https://docs.lsky.pro/docs/v2/quick-start/installation.html#%E5%87%86%E5%A4%87%E5%AE%89%E8%A3%85

**Comment by Jerry12228** [comment]
> https://docs.lsky.pro/docs/v2/quick-start/installation.html#%E5%87%86%E5%A4%87%E5%AE%89%E8%A3%85

谢谢,不过现在上传图片后访问图片url报404
伪静态已正常配置
