### ISSUE TITLE
使用数据库PostgreSQL安装出错：could not find driver ，，，

### ISSUE THREAD

**Issue by spysir** [lsky-org/lsky-pro#485]
![lskypro](https://user-images.githubusercontent.com/59646715/179439254-20eff25f-09b0-4e7e-8d33-74e6348d3015.jpg)
PostgreSQL已经安装成功，就是在WEB界面连接数据库时出错，大佬帮看看是不是PHP缺失什么扩展了

**Comment by wisp-x** [comment]
数据库要先创建好。
