### ISSUE TITLE
跨域问题

### ISSUE THREAD

**Issue by Admsec** [lsky-org/lsky-pro#494]
我是用的 docker + nginx 反向代理的方式
![image](https://user-images.githubusercontent.com/86643414/181934849-9af44422-d94c-499a-8319-bcbdf7544d95.png)
想用来当本地图床，但是似乎显示跨域了。
![image](https://user-images.githubusercontent.com/86643414/181934774-04f130cb-3692-489a-b201-cbe3c6012f6a.png)
我该怎么办？

**Comment by hausen1012** [comment]
docker exec -it lskypro sed -i '32 a \\\Illuminate\\Support\\Facades\\URL::forceScheme('"'"'https'"'"');' /var/www/html/app/Providers/AppServiceProvider.php
