### ISSUE TITLE
希望拓展api功能的建议

### ISSUE THREAD

**Issue by Jerry12228** [lsky-org/lsky-pro#495]
希望使用api上传图片的时候可以有参数来选择所上传到的相册
同时,我认为这个功能也应该在web的上传界面有体现

**Comment by hellodk34** [comment]
@Jerry12228 这个功能在付费版上好像有。

**Comment by Kuingsmile** [comment]
> 希望使用api上传图片的时候可以有参数来选择所上传到的相册 同时,我认为这个功能也应该在web的上传界面有体现

@Jerry12228 修改文件/app/Services/ImageService.php第139行：
原代码为：
```
// 图片保存至默认相册(若有)
            if ($albumId = $user->configs->get(UserConfigKey::DefaultAlbum)) {
                if ($user->albums()->where('id', $albumId)->exists()) {
                    $image->album_id = $albumId;
                }
            }
```
修改为：
```
 if ($request->has('album_id')) {
                $image->album_id = $request->input('album_id');
            } else {
            // 图片保存至默认相册(若有)
            if ($albumId = $user->configs->get(UserConfigKey::DefaultAlbum)) {
                if ($user->albums()->where('id', $albumId)->exists()) {
                    $image->album_id = $albumId;
                }
            }
        }
```
然后在使用API接口的时候，请求body的formdata里增加参数‘album_id’，类似于：
```
formdata = FormData.fromMap({
        "file": await MultipartFile.fromFile(path, filename: name),
        "strategy_id": 1,
        "album_id": 4,
      });
```
这样就可以指定相册上传了

**Comment by Jerry12228** [comment]
> > 希望使用api上传图片的时候可以有参数来选择所上传到的相册 同时,我认为这个功能也应该在web的上传界面有体现
> 
> @Jerry12228 修改文件/app/Services/ImageService.php第139行： 原代码为：
> 
> ```
> // 图片保存至默认相册(若有)
>             if ($albumId = $user->configs->get(UserConfigKey::DefaultAlbum)) {
>                 if ($user->albums()->where('id', $albumId)->exists()) {
>                     $image->album_id = $albumId;
>                 }
>             }
> ```
> 
> 修改为：
> 
> ```
>  if ($request->has('album_id')) {
>                 $image->album_id = $request->input('album_id');
>             } else {
>             // 图片保存至默认相册(若有)
>             if ($albumId = $user->configs->get(UserConfigKey::DefaultAlbum)) {
>                 if ($user->albums()->where('id', $albumId)->exists()) {
>                     $image->album_id = $albumId;
>                 }
>             }
>         }
> ```
> 
> 然后在使用API接口的时候，请求body的formdata里增加参数‘album_id’，类似于：
> 
> ```
> formdata = FormData.fromMap({
>         "file": await MultipartFile.fromFile(path, filename: name),
>         "strategy_id": 1,
>         "album_id": 4,
>       });
> ```
> 
> 这样就可以指定相册上传了



> > 希望使用api上传图片的时候可以有参数来选择所上传到的相册 同时,我认为这个功能也应该在web的上传界面有体现
> 
> @Jerry12228 修改文件/app/Services/ImageService.php第139行： 原代码为：
> 
> ```
> // 图片保存至默认相册(若有)
>             if ($albumId = $user->configs->get(UserConfigKey::DefaultAlbum)) {
>                 if ($user->albums()->where('id', $albumId)->exists()) {
>                     $image->album_id = $albumId;
>                 }
>             }
> ```
> 
> 修改为：
> 
> ```
>  if ($request->has('album_id')) {
>                 $image->album_id = $request->input('album_id');
>             } else {
>             // 图片保存至默认相册(若有)
>             if ($albumId = $user->configs->get(UserConfigKey::DefaultAlbum)) {
>                 if ($user->albums()->where('id', $albumId)->exists()) {
>                     $image->album_id = $albumId;
>                 }
>             }
>         }
> ```
> 
> 然后在使用API接口的时候，请求body的formdata里增加参数‘album_id’，类似于：
> 
> ```
> formdata = FormData.fromMap({
>         "file": await MultipartFile.fromFile(path, filename: name),
>         "strategy_id": 1,
>         "album_id": 4,
>       });
> ```
> 
> 这样就可以指定相册上传了

大佬你不交pr吗?![GCK}BDF QT9MRB97K_ Y{EL](https://user-images.githubusercontent.com/86408775/200758587-f3447142-ba6f-4f25-a115-6f4a344e6a34.png)
