### ISSUE TITLE
[Bug Report]上传时生成文件名错误

### ISSUE THREAD

**Issue by Suansuan-Keai** [lsky-org/lsky-pro#496]
正在使用2.0.4版本，存储策略为本地，文件命名规则为{filename}
上传文件原名：
![image](https://user-images.githubusercontent.com/69025582/182307017-04c8e2eb-0b44-43d0-84bc-676dda7d50e9.png)
上传后链接中文件名有误
![image](https://user-images.githubusercontent.com/69025582/182307175-2262ce7d-e3b9-4ace-99ca-439134e2f380.png)
但是在“我的图片”页面能正确显示文件名：
![image](https://user-images.githubusercontent.com/69025582/182307818-37907e24-9004-4f92-bee9-c15bc3e5c524.png)

尝试用正确的文件名链接访问会404
![image](https://user-images.githubusercontent.com/69025582/182307606-3b6c1128-113d-42e9-916e-80e59011fe2b.png)

**Comment by Suansuan-Keai** [comment]
![image](https://user-images.githubusercontent.com/69025582/182310174-173f660d-0de7-4fc3-a915-a85bdb86fdaf.png)

**Comment by wisp-x** [comment]
能否稳定复现？只有这张图片会出现这个情况吗？

**Comment by Suansuan-Keai** [comment]
目前只发现这张图片，在我的站点上可以稳定复现

> 能否稳定复现？只有这张图片会出现这个情况吗？

**Comment by Suansuan-Keai** [comment]
@wisp-x 别的图片也出问题了，我感觉跟文件名有关系，这次出问题的文件命以`_admin.png`结尾

**Comment by Suansuan-Keai** [comment]
在我这里`mixin.png` `doing.png` 等都会出问题
