### ISSUE TITLE
webdav存储策略问题

### ISSUE THREAD

**Issue by muziqiu2** [lsky-org/lsky-pro#497]
存储策略中的webdav似乎并不能很好的应用，配置好之后发现无法上传图片，根据自己观察应该是默认上传的目录是没有新建文件夹的权限，是不是可以修改一下webdav上传图片的默认位置

**Comment by Fengyee** [comment]
我也遇到同样的情况，webdav  无法正常上传

**Comment by lsyyktv** [comment]
一样的问题

**Comment by mostcute** [comment]
我有用自己开发的webdav服务，经过后台服务的观察，lsky-pro 访问webdav时无视了访问链接中端口之后的部分 如”/dav/shared“
然后直接进行了文件操作。所以webdav后台会认为路径鉴权失败。
希望作者能修一修，往上看到的lsky博客都是在说webdav无法使用

**Comment by wisp-x** [comment]
@mostcute 感谢反馈，近期比较忙，等过一段时间会进行排查处理。

**Comment by fangdezigu** [comment]
> @mostcute 感谢反馈，近期比较忙，等过一段时间会进行排查处理。

希望尽快解决，这问题都半年多了😂，辛苦了

**Comment by SkysCrystal** [comment]
同希望能尽快修复呀，辛苦啦！

**Comment by SkysCrystal** [comment]
> @mostcute 感谢反馈，近期比较忙，等过一段时间会进行排查处理。

同希望能尽快修复呀，辛苦啦！

**Comment by LeenHawk** [comment]
> > @mostcute 感谢反馈，近期比较忙，等过一段时间会进行排查处理。
> 
> 同希望能尽快修复呀，辛苦啦！
所以，啥时候发新release啊(*/ω＼*)

**Comment by iliweii** [comment]
webdav文件上传问题，参考：https://stackoverflow.com/questions/72365649/necessary-data-rewind-wasnt-possible-with-webdav
![image](https://github.com/lsky-org/lsky-pro/assets/49606885/bfb9cb8b-eac9-485d-b500-1960ebfaa245)
![image](https://github.com/lsky-org/lsky-pro/assets/49606885/27f0578a-3ae5-4045-88e4-2a8d63280e42)
加上一行代码：`'authType' => 1,`就能解决

**Comment by carolcoral** [comment]
> webdav文件上传问题，参考：https://stackoverflow.com/questions/72365649/necessary-data-rewind-wasnt-possible-with-webdav ![image](https://private-user-images.githubusercontent.com/49606885/257039595-bfb9cb8b-eac9-485d-b500-1960ebfaa245.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNTk3NTksIm5iZiI6MTcyOTA1OTQ1OSwicGF0aCI6Ii80OTYwNjg4NS8yNTcwMzk1OTUtYmZiOWNiOGItZWFjOS00ODVkLWI1MDAtMTk2MGViZmFhMjQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDA2MTczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5MGIwOGY2NTUwYjY5MmFhNDM3ODY1ZGE2OWZmODg4YTBmM2ZlN2YyMGI3ZDFmNThlNGQ1ZTY1MTM5OTkyYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qt9PXjEdPOesSDN2-3NtJpzfe_o0Ug7ijWJoANOHsaI) ![image](https://private-user-images.githubusercontent.com/49606885/257039625-27f0578a-3ae5-4045-88e4-2a8d63280e42.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNTk3NTksIm5iZiI6MTcyOTA1OTQ1OSwicGF0aCI6Ii80OTYwNjg4NS8yNTcwMzk2MjUtMjdmMDU3OGEtM2FlNS00MDQ1LTg4ZTQtMmE4ZDYzMjgwZTQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDA2MTczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkNDRmODZiODkyOTJjODk5MjkzNjZlMmIzZTNjOTYzZTNmNjdjNDM2M2E0ZTY0NjhiYjAyM2JlMmUwMDBlMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Hk1B_0DPWtmHvSss6sIGWzi6hR03JmY-vNOS9B1lhWQ) 加上一行代码：`'authType' => 1,`就能解决

还是不行，我在service里面加上了这行代码，并且重启了容器，还是提示上传失败
<img width="835" alt="image" src="https://github.com/user-attachments/assets/0624fcea-8b60-4060-a763-aad39cf5d485">
