### ISSUE TITLE
图床突然无法登陆

### ISSUE THREAD

**Issue by 779505388** [lsky-org/lsky-pro#498]
没有改过密码，图片文件都还在，突然无法登陆，登陆一直密码错误，请问如何解决？

**Comment by wisp-x** [comment]
1.  注册新账号，然后进入数据库找到 `users` 数据表，将管理员账号的 `password` 替换为新账号的 `password`。
2. 如果系统关闭了注册功能，需要进入 `configs` 数据表，找到 `name` 为 `is_enable_registration` 的那条数据，将 `value` 改为数字 1，然后登录服务器终端，进入站点根目录执行命令 `php artisan cache:clear`，然后重复上述第一步的步骤。

**Comment by darvintang** [comment]
Could not open input file: artisan
