### ISSUE TITLE
未能通过创建sqlite数据库的方式安装

### ISSUE THREAD

**Issue by zhheo** [lsky-org/lsky-pro#506]
<img width="677" alt="image" src="https://user-images.githubusercontent.com/33177975/184594839-2e22fd6f-1cbf-4948-8e1b-6a3d68299298.png">

提示：
SQLSTATE[HY000]: General error: 1 no such function: json (SQL: update "strategies" set "updated_at" = 2022-08-15 15:35:20, "configs" = json_patch(ifnull("configs", json('{}')), json({"url":"https:\/\/img.zhheo.com\/i"})))

**Comment by zhheo** [comment]
看到文件已经创建
<img width="766" alt="image" src="https://user-images.githubusercontent.com/33177975/184595103-548a7dad-62fe-4088-a4a1-8c85eae32bef.png">

**Comment by wisp-x** [comment]
https://github.com/lsky-org/lsky-pro/discussions/357

**Comment by zhheo** [comment]
# 创建一个工作目录(可选)
mkdir sqlite3_upgrade
cd sqlite3_upgrade

# 下载源码包(大多发行版升级 sqlite3 都使用源码安装)
wget https://www.sqlite.org/2020/sqlite-autoconf-3320300.tar.gz
# 或者 wget https://docs.iterdaily.com/sqlite-autoconf-3320300.tar.gz

# 解压
tar -xf sqlite-autoconf-3320300.tar.gz

# 进入解压目录,编译安装
cd sqlite-autoconf-3320300
./configure --prefix=/usr/local
make && make install

# 替换系统低版本 sqlite3 启动文件
mv /usr/bin/sqlite3  /usr/bin/sqlite3_old
ln -s /usr/local/bin/sqlite3   /usr/bin/sqlite3
# 添加新版 sqlite3 动态链接库配置文件, 刷新动态链接库缓存
echo "/usr/local/lib" > /etc/ld.so.conf.d/sqlite3.conf
ldconfig

# 如果添加的 library 不在 /lib 或 /usr/lib 下, 但是却没有权限操作写 /etc/ld.so.conf 文件的话, 
# 这时就需要往 export 里写一个全局变量 LD_LIBRARY_PATH, 就可以了, 
# 最后将这个 export 命令写到 bashrc 等配置文件中.
export LD_LIBRARY_PATH="/usr/local/lib"

# 查看新的 sqlite3 版本是否生效
sqlite3 -version
3.32.3

更新成功后需要重启PHP
