### ISSUE TITLE
https的静态资源问题

### ISSUE THREAD

**Issue by guantianlan** [lsky-org/lsky-pro#512]
![24e3093bb103a546741d943ecc6c692](https://user-images.githubusercontent.com/105583455/185508095-944869c5-1eb6-4018-a102-dfc07e645f7a.jpg)
GET https://photo.upton.ltd/css/fontawesome.css net::ERR_ABORTED 404
GET https://photo.upton.ltd/css/fontawesome.css net::ERR_ABORTED 404
GET https://photo.upton.ltd/css/common.css net::ERR_ABORTED 404
GET https://photo.upton.ltd/css/app.css net::ERR_ABORTED 404
GET https://photo.upton.ltd/js/app.js net::ERR_ABORTED 404
Uncaught ReferenceError: $ is not defined

**Comment by guantianlan** [comment]
![778e6a9037b7b740ee722eec8eec056](https://user-images.githubusercontent.com/105583455/185508379-169e5182-2e57-4384-8c33-ed6407e0ca2c.jpg)
在.env上添加了ASSET_URL=https://
![96ccec6b9a78582c9ff7bafc7831b1e](https://user-images.githubusercontent.com/105583455/185508595-b03c53a0-f2d7-4c95-8732-61062dc531e6.jpg)
AppServiceProvider.php上添加了\Illuminate\...('https');
![a50763f55427e9ff9a226e011f5c6e3](https://user-images.githubusercontent.com/105583455/185508661-246d9ffc-3016-4170-86c5-6fae14bdba7b.jpg)
https依旧出现问题

**Comment by guantianlan** [comment]
![150ed55744c7fc529635f7dad100837](https://user-images.githubusercontent.com/105583455/185509121-8c851090-3044-4553-9b17-cdf9d31e9a83.jpg)
我是用nginx进行反代的，用lnmp vhost add添加的站点，这是我的nginx配置

**Comment by guantianlan** [comment]
我是用nginx进行反代，用lnmp vhost add命令添加的站点，这是我nginx的配置
![508b76da26c4ca3aac528a7ef2cd0f7](https://user-images.githubusercontent.com/105583455/185509354-05ec0104-77b5-4b44-97e2-a529a924fae7.jpg)

**Comment by guantianlan** [comment]
解决了

**Comment by jerjupiter** [comment]
> 解决了

按照你这个，我的反向代理也解决了
