### ISSUE TITLE
[版本升级问题] 2.0.4 升级到 17 号刚发布的 2.1 困难 | 提供升级的服务器全国各地域名解析有些问题

### ISSUE THREAD

**Issue by hellodk34** [lsky-org/lsky-pro#513]
![17ce7e9f8889b60fadc7f3e096eb687f.jpg](https://img.gejiba.com/images/17ce7e9f8889b60fadc7f3e096eb687f.jpg)

docker 安装的 Lsky Pro V2.0.4 已经进入容器检查了网络，没问题。

现象：

- 升级失败，域名无法解析
- 有时候检查又说已经是最新版本

容器中 ping

```
# ping downloads.lsky.pro -c 4
ping: downloads.lsky.pro: Name or service not known
```

遇到过的报错信息有

```
Call to undefined function Termwind\renderUsing()
```

```
cURL error 28: Failed to connect to download.lsky.pro port 443: Connection timed out (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://download.lsky.pro/2.1/vendor/phpseclib/phpseclib/phpseclib/File/ASN1/Maps/KeyIdentifier.php
```

等等。

------

现在发现是域名解析有问题。全国各地很多地方都无法解析（截图中是 100% 失败）

![790b2d7909f469b7757f20f0b84b8153.jpg](https://img.gejiba.com/images/790b2d7909f469b7757f20f0b84b8153.jpg)

**Comment by wisp-x** [comment]
手动升级吧，域名用了 cloudflare，https://docs.lsky.pro/docs/free/v2/quick-start/upgrade.html#%E6%89%8B%E5%8A%A8%E5%8D%87%E7%BA%A7

**Comment by hellodk34** [comment]
似乎不是 cloudflare 的问题啊，在美国服务器和俄罗斯服务器上域名都无法解析。

美国：

```
nslookup downloads.lsky.pro
Server:         67.207.67.2
Address:        67.207.67.2#53

** server can't find downloads.lsky.pro: NXDOMAIN
```

俄罗斯：

```
nslookup downloads.lsky.pro
Server:         8.8.8.8
Address:        8.8.8.8#53

** server can't find downloads.lsky.pro: NXDOMAIN
```

不过我昨晚还成功访问了 https://downloads.lsky.pro/ 看起来是 nginx 的静态文件托管。

**Comment by hellodk34** [comment]
那也许就是 cloudflare 那边的域名解析配置问题，有余力的话建议排查一下呀，接下来肯定有更多用户会升级版本，让每个人都手动升级不太现实。这 2.1 版本 17 号才发布。

**Comment by hellodk34** [comment]
啊，刚刚重试这次升级成功了。

另外上面我把域名搞错了很抱歉，是 `download`，不是 `downloads`，我的问题已解决。谢谢。
