### ISSUE TITLE
[优化]更改存储逻辑以优化存储空间

### ISSUE THREAD

**Issue by Jerry12228** [lsky-org/lsky-pro#514]
希望在上传图片时, 如果数据库中有存在校验值与上传图片校验值相同的图片时, 直接将新上传的图像指向已存在文件从而节省空间

**Comment by wisp-x** [comment]
Duplicate of #30 #135

See https://github.com/lsky-org/lsky-pro/commit/406040d9d4ab868331f099b41a612b51b245d22a
