### ISSUE TITLE
webdav | 访问域名怎么填啊

### ISSUE THREAD

**Issue by Yuelioi** [lsky-org/lsky-pro#520]
我看webdav只有 dav地址 用户名 密码 3项

请问咱们这个应该怎么填"访问域名"

**Comment by wisp-x** [comment]
字面意思，上传后的图片的访问域名。

**Comment by Yuelioi** [comment]
> 字面意思，上传后的图片的访问域名。

很怪啊~我其他的webdav应用都可以用,就这个不可以...

我填的
https://pic.yuelili.com/ 
https://pic.yuelili.com/i
https://pic.yuelili.com/upload
还试了不带ssl的,都不行...why

WebDAV用的choudreve网盘
走的是onedrive

---

默认本地是可以的

**Comment by Fengyee** [comment]
> > 字面意思，上传后的图片的访问域名。
> 
> 很怪啊~我其他的webdav应用都可以用,就这个不可以...
> 
> 我填的 https://pic.yuelili.com/ https://pic.yuelili.com/i https://pic.yuelili.com/upload 还试了不带ssl的,都不行...why
> 
> WebDAV用的choudreve网盘 走的是onedrive
> 
> 默认本地是可以的

请问你找到解决方法了嘛？

**Comment by wisp-x** [comment]
测试过 choudreve 的 webdav 无法连接，暂时未找到原因。

**Comment by eepicture** [comment]
我看日志报错：“Unable to check existence”

**Comment by lsyyktv** [comment]
确实不行

**Comment by LeenHawk** [comment]
还是用不了

**Comment by lsyyktv** [comment]
> webdav的访问域名填写网站的地址，图片可以上传到webdav，但是复制图片链接访问的时候会显示404

已经完美解决

**Comment by lsyyktv** [comment]
> > > webdav的访问域名填写网站的地址，图片可以上传到webdav，但是复制图片链接访问的时候会显示404
> > 
> > 
> > 已经完美解决
> 
> 何解？

关键就在域名这个地方
这里有两种方式填写（都用alist dav演示吗，记得alist不要把存图片那个文件夹签名加密了）：

1.填写你图片的DAV下载路径，比如https://x.x.x/d/y
x.x.x是你alist的域名
d是alist的下载参数
y是你alist的挂载盘，也就是你图片保存的地方

2.直接填写你图床的网址，我就是用的这个方式，但是需要在nginx里面把图床网址重定向到你的DAV链接
首先图床后台这样设置
![image](https://github.com/lsky-org/lsky-pro/assets/39065858/aa09004e-dc62-442f-945a-eb5c1be4ad44)
然后宝塔面板把图床重定向到DAV下载地址就行了
![image](https://github.com/lsky-org/lsky-pro/assets/39065858/ea186875-be23-4a4b-a11e-7358ae09f726)

**Comment by VectorZhao** [comment]
> > > > webdav的访问域名填写网站的地址，图片可以上传到webdav，但是复制图片链接访问的时候会显示404
> > > 
> > > 
> > > 已经完美解决
> > 
> > 
> > 何解？
> 
> 关键就在访问域名这个地方 这里有两种方式填写（都用alist dav演示，记得alist不要把存图片那个文件夹签名加密了）：
> 
> 1.填写你图片的DAV下载路径，比如https://x.x.x/d/y x.x.x是你alist的域名 d是alist的下载参数 y是你alist的挂载盘，也就是你图片保存的地方
> 
> 2.直接填写你图床的网址，我就是用的这个方式，但是需要在nginx里面把图床网址重定向到你的DAV链接 首先图床后台这样设置 ![image](https://user-images.githubusercontent.com/39065858/257589384-aa09004e-dc62-442f-945a-eb5c1be4ad44.png) 然后宝塔面板把图床重定向到DAV下载地址就行了 ![image](https://user-images.githubusercontent.com/39065858/257589623-ea186875-be23-4a4b-a11e-7358ae09f726.png)

这样做需要把alist的保存图片的那个文件夹公开，不然就得要求输入用户名和密码

**Comment by lsyyktv** [comment]
> > > > > webdav的访问域名填写网站的地址，图片可以上传到webdav，但是复制图片链接访问的时候会显示404
> > > > 
> > > > 
> > > > 已经完美解决
> > > 
> > > 
> > > 何解？
> > 
> > 
> > 关键就在访问域名这个地方 这里有两种方式填写（都用alist dav演示，记得alist不要把存图片那个文件夹签名加密了）：
> > 1.填写你图片的DAV下载路径，比如https://x.x.x/d/y x.x.x是你alist的域名 d是alist的下载参数 y是你alist的挂载盘，也就是你图片保存的地方
> > 2.直接填写你图床的网址，我就是用的这个方式，但是需要在nginx里面把图床网址重定向到你的DAV链接 首先图床后台这样设置 ![image](https://user-images.githubusercontent.com/39065858/257589384-aa09004e-dc62-442f-945a-eb5c1be4ad44.png) 然后宝塔面板把图床重定向到DAV下载地址就行了 ![image](https://user-images.githubusercontent.com/39065858/257589623-ea186875-be23-4a4b-a11e-7358ae09f726.png)
> 
> 这样做需要把alist的保存图片的那个文件夹公开，不然就得要求输入用户名和密码

并不需要公开，这就等于你给别人分享alist的直链

**Comment by VectorZhao** [comment]
我正在找如何去掉签名，现在访问提示
{"code":401,"message":"expire missing","data":null}

**Comment by VectorZhao** [comment]
> > > > > > webdav的访问域名填写网站的地址，图片可以上传到webdav，但是复制图片链接访问的时候会显示404
> > > > > 
> > > > > 
> > > > > 已经完美解决
> > > > 
> > > > 
> > > > 何解？
> > > 
> > > 
> > > 关键就在访问域名这个地方 这里有两种方式填写（都用alist dav演示，记得alist不要把存图片那个文件夹签名加密了）：
> > > 1.填写你图片的DAV下载路径，比如https://x.x.x/d/y x.x.x是你alist的域名 d是alist的下载参数 y是你alist的挂载盘，也就是你图片保存的地方
> > > 2.直接填写你图床的网址，我就是用的这个方式，但是需要在nginx里面把图床网址重定向到你的DAV链接 首先图床后台这样设置 ![image](https://user-images.githubusercontent.com/39065858/257589384-aa09004e-dc62-442f-945a-eb5c1be4ad44.png) 然后宝塔面板把图床重定向到DAV下载地址就行了 ![image](https://user-images.githubusercontent.com/39065858/257589623-ea186875-be23-4a4b-a11e-7358ae09f726.png)
> > 
> > 
> > 这样做需要把alist的保存图片的那个文件夹公开，不然就得要求输入用户名和密码
> 
> 并不需要公开，你要看清楚访问域名地址是带d参数的直链下载地址，而不是访问文件夹的地址，就等于你给别人发下载直链，难道你还需要站公开文件夹吗？

是这样操作吗？
管理 - 设置 -全局 - 签名所有（关闭)
我还没收到怎么去掉某个文件夹的签名

**Comment by lsyyktv** [comment]
> 我正在找如何去掉签名，现在访问提示 {"code":401,"message":"expire missing","data":null}

先关闭全局签名，再把图床文件夹路径单独添加为一个储存不要设置签名就行了，而其他那些需要签名的储存，在对应储存设置里面单独打开签名就行了，互不影响
![image](https://github.com/lsky-org/lsky-pro/assets/39065858/422a3c72-aee7-4d15-93e7-fe516a6976d8)
![image](https://github.com/lsky-org/lsky-pro/assets/39065858/c7c95962-3dd9-438c-afed-50251e5fd7af)
![image](https://github.com/lsky-org/lsky-pro/assets/39065858/0303f682-5cbc-438e-bbbd-1fe07c87468d)

**Comment by VectorZhao** [comment]
感谢，搞定了。但是有一点，用lskypro的本地存储分享想图片链接在浏览器里可以直接预览，而alist的图片链接目前点开就会弹出下载框。

**Comment by lsyyktv** [comment]
> 感谢，搞定了。但是有一点，用lskypro的本地存储分享的图片链接在浏览器里可以直接预览，而alist的图片链接目前点开就会弹出下载框。

是的，这是唯一一个不好的地方，alist的作者暂时没打算提供图床预览功能。不过如果是博客写文章引用代码之类的，倒是无所谓！

**Comment by VectorZhao** [comment]
> > 感谢，搞定了。但是有一点，用lskypro的本地存储分享的图片链接在浏览器里可以直接预览，而alist的图片链接目前点开就会弹出下载框。
> 
> 是的，这是唯一一个不好的地方，alist的作者暂时没打算提供图床预览功能。不过如果是博客写文章引用代码之类的，倒是无所谓！

嗯嗯，确实博客文章啥的插入图片就够用了。

**Comment by carolcoral** [comment]
请问下，我是docker compose方式部署的lsky，现在配置alist的webdav到lsky，一直提示上传失败呢
<img width="944" alt="image" src="https://github.com/user-attachments/assets/de9ae623-b393-4736-aeea-a3fdca2883a8">

**Comment by carolcoral** [comment]
搞定了，果然，访问地址不能直接用alist的地址，必须做一次转发才行，就很奇怪

**Comment by SDCOM-0415** [comment]
V 2.1这个版本没有认证方式了，不知道为什么已经不能用了
