### ISSUE TITLE
上传psd图片后psd网址报500错误

### ISSUE THREAD

**Issue by luoyu124578** [lsky-org/lsky-pro#539]
上传psd文件后，psd文件url网址为报500错误

**Comment by luoyu124578** [comment]
关闭原图保护后可访问下载

**Comment by wisp-x** [comment]
`storage/logs` 文件夹中有错误日志，放出来看一下。

**Comment by luoyu124578** [comment]
http://150.158.57.204:8888/down/n96Eu3c2SbQi log日志

**Comment by wisp-x** [comment]
开启原图保护后如果是 psd、tif、bmp 文件会使用 imagemagick 转换成 png 格式输出，看日志应该是转换失败了，可以使用下面的命令查看是否支持 psd。
```shell
identify -list format | grep PSD
```

**Comment by luoyu124578** [comment]
好的谢谢
