### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by asmydream** [lsky-org/lsky-pro#547]
麻烦帮忙看一下，点击安装 报错，控制台错误
Error: Request failed with status code 419
app.js:2 Uncaught (in promise) Error: Request failed with status code 419
    at e.exports (app.js:2:6272)
    at e.exports (app.js:2:8676)
    at XMLHttpRequest._ (app.js:2:825)

**Comment by asmydream** [comment]
已解决

**Comment by hausen1012** [comment]
请问啥问题
