### ISSUE TITLE
图床安装错误

### ISSUE THREAD

**Issue by wolovejing** [lsky-org/lsky-pro#549]
安装环境 宝塔
已确认数据库用户名什么的都正确
![image](https://user-images.githubusercontent.com/30975494/196023608-cfef7ec6-8e8a-4dc4-a1a1-f7be87260041.png)

**Comment by wolovejing** [comment]
MySQL 5.6.50

**Comment by Jerry12228** [comment]
请参考[安装要求](https://docs.lsky.pro/docs/free/v2/#%E5%AE%89%E8%A3%85%E8%A6%81%E6%B1%82)
要求MySQL5.7+
