### ISSUE TITLE
用户通过优惠券购买完用户组以后统计错误(或显示错误)

### ISSUE THREAD

**Issue by anzhiyu-c** [lsky-org/lsky-pro#572]
问题现象：用户买完A用户组以后，该用户实际上已经属于A用户组了，但是管理员在后台查看`角色组`下的用户数量，发现该用户依然处于原来的游客组，包括统计中也是在游客组中。

**Comment by wisp-x** [comment]
![image](https://user-images.githubusercontent.com/22728201/203944505-37bf427f-8602-4377-9f53-9d4d6fa32396.png)

**Comment by wisp-x** [comment]
统计那里目前只会根据原始用户组进行统计，后面我看看怎么优化展示。

**Comment by anzhiyu-c** [comment]
> 统计那里目前只会根据原始用户组进行统计，后面我看看怎么优化展示。

麻烦您了，这个Issues我先关闭了，感谢您。
