### ISSUE TITLE
需要怎样设置才能让原来的图片地址自动跳转到带i前缀的地址

### ISSUE THREAD

**Issue by liub1934** [lsky-org/lsky-pro#573]
升级前地址：https://pic.iqy.ink/2022/11/25/6380cba01e537.png
升级后地址：https://pic.iqy.ink/i/2022/11/25/6380cba01e537.png
升级后域名后面都带有i前缀，我原来的图片地址是不带i前缀的，有啥规则或者方法能自动跳转到带i的前缀地址吗。

**Comment by yijiangchengming** [comment]
试试nginx的重写功能

**Comment by penndu** [comment]
或者可以通过修改数据库使生成地址中没有i前缀，去不图床采用该种方法！

**Comment by liub1934** [comment]
使用正则匹配+301重定向，有需要的拿去使用。

```
if ($request_uri ~* ^/[0-9]+/[0-9]+/[0-9]+/.+) {
    return 301 https://$host/i$request_uri;
}
```

<img width="637" alt="image" src="https://user-images.githubusercontent.com/29849550/218297184-e29d5fe2-27a9-478b-8fbb-c70739be9396.png">
