### ISSUE TITLE
Step 2 > 配置数据库和管理员账号出现问题

### ISSUE THREAD

**Issue by eramicro** [lsky-org/lsky-pro#584]
![图片](https://user-images.githubusercontent.com/44019323/209275102-ce37ace9-8c68-43a1-8246-6da4a0e6b761.png)
mysql版本是5.7，安装要求也仔细看了，数据库和数据库用户也排查了（有权限），搞不懂哪里出现了问题。

**Comment by wisp-x** [comment]
检查一下连接地址和端口。

**Comment by eramicro** [comment]
嗯嗯 正在检查，别的站没问题，刚搭建哈

**Comment by eramicro** [comment]
排查完，发现是面板把默认的端口号改了.............................................................
