### ISSUE TITLE
第三方存储能不能加上backblaze b2 或者aws s3 之类的？

### ISSUE THREAD

**Issue by staticfilestorage** [lsky-org/lsky-pro#60]

**Comment by wisp-x** [comment]
后面要是有时间就加

**Comment by xspoco** [comment]
同求添加。backblaze b2还不错

**Comment by Creling** [comment]
同求，希望可以在阿里oos的基础上改一套s3 compatible后端，这样子很多第三方存储都可以直接使用了，不需要针对每个存储特意定制。

**Comment by billy74** [comment]
哈哈 其实支持标准S3协议基本可以秒一大半市面上的对象存储了，七牛 腾讯 阿里。。。不用整那么多 一个S3协议通吃 多好
