### ISSUE TITLE
API删除图片提示成功，实际图片还是在相册显示

### ISSUE THREAD

**Issue by 759071793** [lsky-org/lsky-pro#605]
![image](https://user-images.githubusercontent.com/23308600/215296822-7907ac30-d975-49d3-8637-2543dee49e21.png)

**Comment by wisp-x** [comment]
接口删除图片总是会返回成功，删除后还在就说明参数或参数值传错了。

**Comment by 759071793** [comment]
我特意在wordpress数据库保存了图片上传的KEY值，
![image](https://user-images.githubusercontent.com/23308600/215303722-34ee019e-67f4-462b-b128-7f0d60463cad.png)
![image](https://user-images.githubusercontent.com/23308600/215303733-faad8bc2-d75b-4996-8d7f-248b386740e6.png)
然后我先尝试单独用一个图片的key去删除图片：
![image](https://user-images.githubusercontent.com/23308600/215303853-3dea5be7-c54d-489f-8c7d-99d5ebdeecf5.png)
返回值：
![image](https://user-images.githubusercontent.com/23308600/215303877-f60c68fc-28d3-4956-be70-249258c20412.png)
但是图片一张都没少：
![image](https://user-images.githubusercontent.com/23308600/215303889-83e68bc3-e48a-4883-8f12-cd31f4515319.png)

**Comment by 759071793** [comment]
我尝试使用不存在的key，返回:
![image](https://user-images.githubusercontent.com/23308600/215304402-1f791c2a-af28-4e21-9c0d-23dd928ba2b4.png)
但是确实key有时候乱写也会返回true
