### ISSUE TITLE
强烈建议可以增加github做图床存储选项吗？

### ISSUE THREAD

**Issue by mvfeng** [lsky-org/lsky-pro#613]
强烈建议可以增加github做图床存储选项吗？

**Comment by kanodaisuki** [comment]
善待github[反馈问题](https://docs.lsky.pro/docs/free/v2/#%E5%8F%8D%E9%A6%88%E9%97%AE%E9%A2%98)

**Comment by akatsukiro** [comment]
能不能别霍霍GitHub了，还嫌不够吗？

**Comment by akatsukiro** [comment]
> > 能不能别霍霍GitHub了，还嫌不够吗？
> 
> 什么叫霍霍？github做图床怎么就霍霍了，也有开源的github做图床项目，star挺多的，难道不是正常需求吗?

那建议您还是去使用您所谓的“github做图床项目”吧，Lsky 过去，现在，将来都不会考虑使用GitHub存储。
