### ISSUE TITLE
通过API上传图片，返回服务异常，请稍后再试

### ISSUE THREAD

**Issue by xiaqiqi-1** [lsky-org/lsky-pro#624]
header = {
        "Authorization":"Bearer "+api_key,
        "Content-Type": "multipart/form-data",
        "Accept":"application/json"
    }
    #上传文件
    file=open(image_path,'rb')
    response = requests.post(api_url, headers=header,files={"file":file})

**Comment by wisp-x** [comment]
检查 `storage/logs` 日志文件。
