### ISSUE TITLE
无法上传图片到 AList 的 Webdav 

### ISSUE THREAD

**Issue by SkysCrystal** [lsky-org/lsky-pro#628]
报错内容如下：
`prod.ERROR: 保存图片时出现异常 {"file":"/path-to-lsky/vendor/league/flysystem/src/UnableToCheckExistence.php","line":14,"message":"Unable to check existence for: 2023/03/07","trace":"#0 /path-to-lsky/vendor/league/flysystem-webdav/WebDAVAdapter.php(104): League\\Flysystem\\UnableToCheckExistence::forLocation()`

希望能兼容 [AList](https://github.com/alist-org/alist) 的 Webdav 。这样存储方式的扩展就会更丰富，谢谢！

**Comment by SkysCrystal** [comment]
类似问题 #497

**Comment by awinds** [comment]
试了master分支还是存在同样的问题
