### ISSUE TITLE
Gravatar镜像cravatar.cn 不稳定

### ISSUE THREAD

**Issue by sepmoecat** [lsky-org/lsky-pro#634]
镜像不稳定 经常502 建议后台添加更换gravatar服务器功能

**Comment by WuMe-sicx** [comment]
我的建议是自建反代

**Comment by sepmoecat** [comment]
> 我的建议是自建反代

是的 目前在使用自建的反代，就是希望后台能提供一个切换的功能 提供更多的gravatar公共镜像服务器选择

**Comment by f2010525** [comment]
之前是由小团队公益服务，稳定性比较长，目前 Cravatar 头像正在更换服务器机房，cravatar.cn 后续将由文派开源团队运营。
