### ISSUE TITLE
图片管理问题

### ISSUE THREAD

**Issue by musnows** [lsky-org/lsky-pro#640]
我有一张图片被恶意请求，我想在lsky图片管理里面搜索这个图片，结果图片url竟然不支持搜索这张图？？？
```
域名/i/2023/03/640f0dcc662f2.png
用640f0dcc662f2无法搜到该图片
```
真切希望加上这个功能，为了解决这个问题，我得上ssh去后台直接改这个图片的名字或者删除它，相比于直接在web后台搜索，还是麻烦了一点。

lsky版本最新v2.1

我看到了这个，也是相似的问题 https://github.com/lsky-org/lsky-pro/issues/509

麻烦各位开发者大佬了

**Comment by wisp-x** [comment]
已经支持，暂时不发布新版本，可以尝试自己通过 05af7dffb815cfc64b04c3621391345f968fd053 内容来修改代码实现。
