### ISSUE TITLE
无法访问静态资源

### ISSUE THREAD

**Issue by Redmomn** [lsky-org/lsky-pro#652]
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/109732988/233519225-65009a46-9dad-4212-8381-53fe36a4c1a3.png">
控制台报错，js和css全报404错误
<img width="477" alt="image" src="https://user-images.githubusercontent.com/109732988/233519279-0a27effe-8987-4dfd-82a4-20d39b68ae79.png">
网站是nginx+php部署的
nginx配置
<img width="486" alt="image" src="https://user-images.githubusercontent.com/109732988/233541430-6f425a3a-f0a1-44be-abf2-688e4fae786c.png">

php版本是8.0.28，扩展和函数均已达到要求

**Comment by zjy2931** [comment]
怎么搞定的
