### ISSUE TITLE
新建本地存储策略上传图片会有双份

### ISSUE THREAD

**Issue by izelle** [lsky-org/lsky-pro#670]
安装图床后删除了默认本地存储策略
新建了一个存储策略，指定了本地一个文件夹pictures，位置/home/pictures
当上传图片后，文件夹中显示该上传的图片，说明新建的存储策略生效
但是www/wwwroot/xxx.xxx.com/public/uploads中还存在同样的一份
等于说同一个图片在硬盘中存放两份，这样太占用存储空间啊
为何会这样的呢？如何有效避免呢？难道要必须指定系统默认存储路径才可以吗

**Comment by wisp-x** [comment]
建议了解一下文件系统中，符号链接(symlink)的作用。
