### ISSUE TITLE
对单点自建minio存储的支持差到离谱

### ISSUE THREAD

**Issue by WindyCloudCute** [lsky-org/lsky-pro#683]
## 使用如下配置会出现这种奇葩错误,自建的根本没有三级子域名为什么就不能直接用二级域名直接连接,如果储存桶里有斜杠之类的符号的时候,终于不用三级域名了,但是出现了个更奇葩的证书错误。
![image](https://github.com/lsky-org/lsky-pro/assets/22683776/f4c54608-b42e-478f-ad3a-397085b37e11)

`[23:07:43] LOG.error: 保存图片时出现异常 {"file":"\/www\/wwwroot\/lsky-pro\/vendor\/league\/flysystem\/src\/UnableToWriteFile.php","line":24,"message":"Unable to write file at location: 2023\/06\/30\/649eefbf71747.jpg. Error executing \"PutObject\" on \"https:\/\/lskypro-data.wos.windycloud.cn:9000\/2023\/06\/30\/649eefbf71747.jpg\"; AWS HTTP error: cURL error 60: SSL: no alternative certificate subject name matches target host name 'lskypro-data.wos.windycloud.cn' (see https:\/\/curl.haxx.se\/libcurl\/c\/libcurl-errors.html) for https:\/\/lskypro-data.wos.windycloud.cn:9000\/2023\/06\/30\/649eefbf71747.jpg","trace":"#0 \/www\/wwwroot\/lsky-pro\/vendor\/league\/flysystem-aws-s3-v3\/AwsS3V3Adapter.php(208): League\\Flysystem\\UnableToWriteFile::atLocation()\n#1 \/www\/wwwroot\/lsky-pro\/vendor\/league\/flysystem-aws-s3-v3\/AwsS3V3Adapter.php(249): League\\Flysystem\\AwsS3V3\\AwsS3V3Adapter->upload()\n#2 \/www\/wwwroot\/lsky-pro\/vendor\/league\/flysystem\/src\/Filesystem.php(68): League\\Flysystem\\AwsS3V3\\AwsS3V3Adapter->writeStream()\n#3 \/www\/wwwroot\/lsky-pro\/app\/Services\/ImageService.php(214): League\\Flysystem\\Filesystem->writeStream()\n#4 \/www\/wwwroot\/lsky-pro\/app\/Http\/Controllers\/Controller.php(129): App\\Services\\ImageService->store()\n#5 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Controller.php(54): App\\Http\\Controllers\\Controller->upload()\n#6 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()\n#7 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Route.php(261): Illuminate\\Routing\\ControllerDispatcher->dispatch()\n#8 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Route.php(204): Illuminate\\Routing\\Route->runController()\n#9 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(725): Illuminate\\Routing\\Route->run()\n#10 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()\n#11 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Middleware\/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()\n#12 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()\n#13 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()\n#14 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()\n#15 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/View\/Middleware\/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()\n#16 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()\n#17 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Session\/Middleware\/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()\n#18 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Session\/Middleware\/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()\n#19 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle()\n#20 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Cookie\/Middleware\/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()\n#21 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()\n#22 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Cookie\/Middleware\/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()\n#23 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()\n#24 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()\n#25 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(726): Illuminate\\Pipeline\\Pipeline->then()\n#26 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(703): Illuminate\\Routing\\Router->runRouteWithinStack()\n#27 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(667): Illuminate\\Routing\\Router->runRoute()\n#28 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(656): Illuminate\\Routing\\Router->dispatchToRoute()\n#29 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()\n#30 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()\n#31 \/www\/wwwroot\/lsky-pro\/vendor\/barryvdh\/laravel-debugbar\/src\/Middleware\/InjectDebugbar.php(66): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()\n#32 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(180): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle()\n#33 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()\n#34 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()\n#35 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()\n#36 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()\n#37 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()\n#38 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()\n#39 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()\n#40 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()\n#41 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()\n#42 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()\n#43 \/www\/wwwroot\/lsky-pro\/vendor\/fruitcake\/laravel-cors\/src\/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()\n#44 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(180): Fruitcake\\Cors\\HandleCors->handle()\n#45 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Http\/Middleware\/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()\n#46 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()\n#47 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()\n#48 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()\n#49 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()\n#50 \/www\/wwwroot\/lsky-pro\/public\/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()\n#51 {main}"}`

#### 如果使用这个配置
![image](https://github.com/lsky-org/lsky-pro/assets/22683776/0388a28f-a280-4df7-89b7-7f23992c177f)

`[23:08:45] LOG.error: 保存图片时出现异常 {"file":"\/www\/wwwroot\/lsky-pro\/vendor\/league\/flysystem\/src\/UnableToWriteFile.php","line":24,"message":"Unable to write file at location: 2023\/06\/30\/649eeffd8edde.jpg. Error executing \"PutObject\" on \"https:\/\/wos.windycloud.cn:9000\/lskypro-data%2Fdata\/2023\/06\/30\/649eeffd8edde.jpg\"; AWS HTTP error: Client error: `PUT https:\/\/wos.windycloud.cn:9000\/lskypro-data%2Fdata\/2023\/06\/30\/649eeffd8edde.jpg` resulted in a `403 Forbidden` response:\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>SignatureDoesNotMatch<\/Code><Message>The request signature we calcul (truncated...)\n SignatureDoesNotMatch (client): The request signature we calculated does not match the signature you provided. Check your key and signing method. - <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>SignatureDoesNotMatch<\/Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.<\/Message><Key>2023\/06\/30\/649eeffd8edde.jpg<\/Key><BucketName>lskypro-data%2Fdata<\/BucketName><Resource>\/lskypro-data\/data\/2023\/06\/30\/649eeffd8edde.jpg<\/Resource><Region>cn-gx-hc1<\/Region><RequestId>176D785105595008<\/RequestId><HostId>e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855<\/HostId><\/Error>","trace":"#0 \/www\/wwwroot\/lsky-pro\/vendor\/league\/flysystem-aws-s3-v3\/AwsS3V3Adapter.php(208): League\\Flysystem\\UnableToWriteFile::atLocation()\n#1 \/www\/wwwroot\/lsky-pro\/vendor\/league\/flysystem-aws-s3-v3\/AwsS3V3Adapter.php(249): League\\Flysystem\\AwsS3V3\\AwsS3V3Adapter->upload()\n#2 \/www\/wwwroot\/lsky-pro\/vendor\/league\/flysystem\/src\/Filesystem.php(68): League\\Flysystem\\AwsS3V3\\AwsS3V3Adapter->writeStream()\n#3 \/www\/wwwroot\/lsky-pro\/app\/Services\/ImageService.php(214): League\\Flysystem\\Filesystem->writeStream()\n#4 \/www\/wwwroot\/lsky-pro\/app\/Http\/Controllers\/Controller.php(129): App\\Services\\ImageService->store()\n#5 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Controller.php(54): App\\Http\\Controllers\\Controller->upload()\n#6 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()\n#7 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Route.php(261): Illuminate\\Routing\\ControllerDispatcher->dispatch()\n#8 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Route.php(204): Illuminate\\Routing\\Route->runController()\n#9 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(725): Illuminate\\Routing\\Route->run()\n#10 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()\n#11 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Middleware\/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()\n#12 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()\n#13 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()\n#14 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()\n#15 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/View\/Middleware\/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()\n#16 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()\n#17 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Session\/Middleware\/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()\n#18 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Session\/Middleware\/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()\n#19 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle()\n#20 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Cookie\/Middleware\/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()\n#21 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()\n#22 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Cookie\/Middleware\/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()\n#23 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()\n#24 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()\n#25 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(726): Illuminate\\Pipeline\\Pipeline->then()\n#26 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(703): Illuminate\\Routing\\Router->runRouteWithinStack()\n#27 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(667): Illuminate\\Routing\\Router->runRoute()\n#28 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(656): Illuminate\\Routing\\Router->dispatchToRoute()\n#29 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()\n#30 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()\n#31 \/www\/wwwroot\/lsky-pro\/vendor\/barryvdh\/laravel-debugbar\/src\/Middleware\/InjectDebugbar.php(66): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()\n#32 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(180): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle()\n#33 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()\n#34 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()\n#35 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()\n#36 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()\n#37 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()\n#38 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()\n#39 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()\n#40 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()\n#41 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()\n#42 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()\n#43 \/www\/wwwroot\/lsky-pro\/vendor\/fruitcake\/laravel-cors\/src\/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()\n#44 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(180): Fruitcake\\Cors\\HandleCors->handle()\n#45 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Http\/Middleware\/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()\n#46 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()\n#47 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()\n#48 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()\n#49 \/www\/wwwroot\/lsky-pro\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()\n#50 \/www\/wwwroot\/lsky-pro\/public\/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()\n#51 {main}"}`

**Comment by WindyCloudCute** [comment]
> 好了现在大家都知道你不会用了，没必要贬低程序来彰显自己多牛逼。
> 
> > BTW，我minio用的好好的，群友也用的好好的，怎么到你这就不行了呢？

我不会用又怎么了？我还不能发issues问了？这个问题你解答了还是怎的？和着我用不了minio我还不会配置cos？瞧把你能的我要是能找到一个像样的教程我会发issues？现实生活不如意了开始到社区上找存在感了？我有不承认我不会用么？还是你觉得我不会用来找存在感了？我有贬低么？这东西本来配置就不好理解我还不能发了？瞧把您给能的，我也承认我发的issues标题确实是我错在先，但是我需要你来上纲上线表达你那突破天际的优越感？

**Comment by WindyCloudCute** [comment]
> 好了现在大家都知道你不会用了，没必要贬低程序来彰显自己多牛逼。
> 
> > BTW，我minio用的好好的，群友也用的好好的，怎么到你这就不行了呢？

用于非商业用途，是不是还要买个泛域名ssl配置一通，嘎嘎牛逼才能在贵社区提问？我就搞不懂了，如果你觉得不爽你可以选择当傻逼不回或者当作没看到，上来输出一下让对方也不爽还在这说啊这下所有人都知道你不会用啊吧啊吧，你是觉得你会用一个程序你很能耐了还是咋地，别人不会就不配用了吗，还是你觉得一个人不会某一样东西别人看见了很丢人，问了就证明那个人是傻逼是弱智。

**Comment by wisp-x** [comment]
和平交流，别吵架。
可以在 https://github.com/lsky-org/lsky-pro/blob/911275c13b038c7a8b710de44664f23887eeb6f6/app/Services/ImageService.php#L356 这一行下面加一行配置解决：
```php
// ...
'use_path_style_endpoint' => true,
// ...
```
参数解释：
是否使用路径样式（Path-Style）
1. 虚拟主机样式（Virtual Hosted-Style）URL：这是默认的 URL 样式，它基于存储桶和对象的 DNS 名称。例如 https://bucket-name.s3.amazonaws.com/object-key
2. 路径样式（Path-Style）URL：这种 URL 样式在主机名后使用存储桶名称作为路径的一部分。例如 https://s3.amazonaws.com/bucket-name/object-key

true 则表示使用路径样式（Path-Style），默认为 false

**Comment by WindyCloudCute** [comment]
谢谢您,修改完成后已经成功了。

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年7月4日 16:34
收件人: ***@***.***>
抄送: ***@***.***>; State ***@***.***>
主题: Re: [lsky-org/lsky-pro] 对单点自建minio存储的支持差到离谱 (Issue #683)


和平交流，别吵架。
可以在 https://github.com/lsky-org/lsky-pro/blob/911275c13b038c7a8b710de44664f23887eeb6f6/app/Services/ImageService.php#L356 这一行下面加一行配置解决：

// ...

'use_path_style_endpoint' => true,

// ...

参数解释：
是否使用路径样式（Path-Style）

  1.  虚拟主机样式（Virtual Hosted-Style）URL：这是默认的 URL 样式，它基于存储桶和对象的 DNS 名称。例如 https://bucket-name.s3.amazonaws.com/object-key
  2.  路径样式（Path-Style）URL：这种 URL 样式在主机名后使用存储桶名称作为路径的一部分。例如 https://s3.amazonaws.com/bucket-name/object-key

true 则表示使用路径样式（Path-Style），默认为 false

―

**Comment by WindyCloudCute** [comment]
> 和平交流，别吵架。 可以在
> 
> https://github.com/lsky-org/lsky-pro/blob/911275c13b038c7a8b710de44664f23887eeb6f6/app/Services/ImageService.php#L356
> 
> 这一行下面加一行配置解决：
> ```
> // ...
> 'use_path_style_endpoint' => true,
> // ...
> ```
> 
> 参数解释： 是否使用路径样式（Path-Style）
> 
> 1. 虚拟主机样式（Virtual Hosted-Style）URL：这是默认的 URL 样式，它基于存储桶和对象的 DNS 名称。例如 https://bucket-name.s3.amazonaws.com/object-key
> 2. 路径样式（Path-Style）URL：这种 URL 样式在主机名后使用存储桶名称作为路径的一部分。例如 https://s3.amazonaws.com/bucket-name/object-key
> 
> true 则表示使用路径样式（Path-Style），默认为 false

已经弄好了 谢谢您
