### ISSUE TITLE
通过API上传至非本机存储策略后，本机会存在API上传的图片

### ISSUE THREAD

**Issue by xiaqijun** [lsky-org/lsky-pro#688]
1、/www/wwwroot/tuchuang.dongling.xyz/public/thumbnails,此路径下的文件是什么作用？
2、通过API上传至非本机的存储策略，发现在此文件下也会有相同文件内容，删除后未影响图床使用

**Comment by akatsukiro** [comment]
https://translate.google.com/?sl=en&tl=zh-CN&text=thumbnail&op=translate

**Comment by xiaqijun** [comment]
图片总共上传了37个G，缩略图有34个G

**Comment by wisp-x** [comment]
https://github.com/lsky-org/lsky-pro/blob/911275c13b038c7a8b710de44664f23887eeb6f6/app/Services/ImageService.php#L571
将这一行的数字 60 改为 40 或更低，付费版本的在文件 app/Jobs/ImageGenerateThumbnail.php 第 77 行；不建议删除缩略图，会导致图片管理页面流量剧增。

**Comment by xiaqijun** [comment]
> 

我发现了这个问题，删除后会直接请求图片所在的URL地址

**Comment by xiaqijun** [comment]
> https://github.com/lsky-org/lsky-pro/blob/911275c13b038c7a8b710de44664f23887eeb6f6/app/Services/ImageService.php#L571
> 
> 
> 将这一行的数字 60 改为 40 或更低，付费版本的在文件 app/Jobs/ImageGenerateThumbnail.php 第 77 行；不建议删除缩略图，会导致图片管理页面流量剧增。
感谢解答
