### ISSUE TITLE
使用 MySQL 8 时安装失败

### ISSUE THREAD

**Issue by haoliplus** [lsky-org/lsky-pro#710]
update ur时失败。我去数据库手动执行了下，在MySQL8版本执行该命令需要对连接增加引号。

`SQLSTATE[22032]: <>: 3141 Invalid JSON text in argument 1 to function cast_as_json: "Invalid value." at position 0. (SQL: update `strategies` set `configs` = json_set(`configs`, '$."url"', https://a.example.com/i), `strategies`.`updated_at` = 2023-08-23 11:45:22)`

对php不太熟，不过搜索了下，具体代码应该是：
https://github.com/lsky-org/lsky-pro/blob/911275c13b038c7a8b710de44664f23887eeb6f6/app/Http/Controllers/Controller.php#L113

安装要求mysql 5.7+， 8在这个支持范围吗（业务的云数据库不太方便更换版本）？不太清楚有没有其他问题。

**Comment by akatsukiro** [comment]
更新 MySQL 的版本吧，这应该是 MySQL8 前期版本的一个BUG。

**Comment by haoliplus** [comment]
https://github.com/laravel/framework/discussions/35643
https://bugs.mysql.com/bug.php?id=101284

是mysql8.0.22版本bug
