### ISSUE TITLE
企业版自己 build 镜像，启动后 403

### ISSUE THREAD

**Issue by xiaogliu** [lsky-org/lsky-pro#717]
## 问题描述
使用 docker 自己 build 镜像，容器启动后 403。其中 Nginx 通过将授权子域名反向代理到 Lsky 容器。

```
server {
    # 监听 443 https 端口
    listen 443 ssl;
    server_name img.example.com;  # 授权子域名

    location / {
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   Host              $http_host;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_pass  http://lsky-ee:8090; # 反向代理到 Lsky 域名
    }
}
```

已根据 [第三步，初始化配置](https://docs.lsky.pro/docs/enterprise/v1/quick-start/installation.html#%E7%AC%AC%E4%B8%89%E6%AD%A5-%E5%88%9D%E5%A7%8B%E5%8C%96%E9%85%8D%E7%BD%AE) 教程进行了配置。

![image](https://github.com/lsky-org/lsky-pro/assets/15944323/2ec4e8e2-b2e4-48b2-a0fb-140e440b13cd)

## 猜想

反向代理导致鉴权失败？希望作者可以解答下，感谢~

**Comment by wisp-x** [comment]
如果确定配置填写的是完整的，出现这个错误可能是没有读取到 `.env` 文件里的配置，看一下 PHP 的 `getenv` 和 `putenv` 函数是否被禁用了，还有该文件权限是否正确；build 镜像可能会导致源码泄露，不建议你这样做。

**Comment by xiaogliu** [comment]
感谢，确实是因为没有读取到 `.env`！已解决 👍 

> build 镜像可能会导致源码泄露，不建议你这样做。

我是私有部署 docker 镜像，方便 CICD，不会暴露给外部
