### ISSUE TITLE
企业版 bug: 图片第一次上传，thumbnail image 无法生成，thumbnail url 为原图 url

### ISSUE THREAD

**Issue by xiaogliu** [lsky-org/lsky-pro#731]
## 问题描述
企业版 bug: 图片第一次上传，thumbnail image 无法生成，thumbnail url 为原图 url

![image](https://github.com/lsky-org/lsky-pro/assets/15944323/968d8073-3baf-47d6-9fe6-b4f22afb4eb8)
![image](https://github.com/lsky-org/lsky-pro/assets/15944323/484a2104-a92b-4cad-89af-6bda1f72280c)

但如果图片上传过一次，thumbnail image url 可正常生成。

**Comment by wisp-x** [comment]
付费版本，生成缩略图是异步的，刚上传完不会立即生成缩略图。

**Comment by xiaogliu** [comment]
我现在有个需求：通过 API 上传图片后需要获取缩略图 URL，有什么办法吗（目前异步导致上传后无法获取到）？

**Comment by wisp-x** [comment]
> 我现在有个需求：通过 API 上传图片后需要获取缩略图 URL，有什么办法吗（目前异步导致上传后无法获取到）？

需要修改代码，尝试将：`/app/Services/ImageService.php` 文件的第 742 行，修改为：
```php
ImageGenerateThumbnail::dispatchSync($image, $max, $force);
```
这样的话生成缩略图操作应该会同步执行，但是会影响上传速度，以及在上传时会消耗更多的内存。

**Comment by xiaogliu** [comment]
成功了，谢谢 👍
