### ISSUE TITLE
企业版 Thumbnail 图片大小问题 

### ISSUE THREAD

**Issue by xiaogliu** [lsky-org/lsky-pro#732]
# 问题描述

如果原图图片本身较小，比如 Webp 格式，50kb，thumbnail 图片甚至比原图大。

# 期待解决问题

1. 企业版可否配置 Thumbnail 图片大小？
2. 企业版是否可以调整 Thumbnail 图片类型？

感谢！

**Comment by wisp-x** [comment]
`/app/Jobs/ImageGenerateThumbnail.php` 文件第 77 行，后面的数字 40 就是图片质量，数字越低质量越低，最大 100。

**Comment by xiaogliu** [comment]
Thumbnail 图片的类型可以改吗？比如从 png 改为 jpg
