### ISSUE TITLE
怎么通过Alist挂载阿里云盘的Webdav？

### ISSUE THREAD

**Issue by Whitea-Ann** [lsky-org/lsky-pro#747]
想挂载阿里云盘的Webdav当图床用，信息都填好了，上传图片总是失败，求大佬解决。
![image](https://github.com/lsky-org/lsky-pro/assets/66663049/397f120f-4263-4e67-9261-7f648858cc08)

**Comment by qbning** [comment]
请问大佬是怎么解决的
