### ISSUE TITLE
webDav挂载后不显示

### ISSUE THREAD

**Issue by loohalh** [lsky-org/lsky-pro#767]
我是用宝塔安装的，没有设置Nginx 配置项， alist和图床没在一台服务器上，alits已经配置正确了，访问能正常访问http://www.alist.com/dav/image/xxxx.png，可以正常下载。在图床添加存储，访问域名是：http://www.tuchuang.com/img, 连接地址是http://www.alist.com, 认证方式是basic,路径前缀是/dav/image,然后填写图床账号密码(确认无误),添加后吐司提示添加成功，但是无法右上角存贮哪儿不显示webDav 这个是什么样原因来着

**Comment by wisp-x** [comment]
你的账号所在的用户组需要关联该储存策略才会显示。

**Comment by loohalh** [comment]
> 你的账号所在的用户组需要关联该储存策略才会显示。

刚刚检查了下，目前只有一个默认的用户和用户组，配置的时候也设置了关联，是不是还有其他原因
<img width="1189" alt="image" src="https://github.com/lsky-org/lsky-pro/assets/16890588/52bcfb42-5e69-4ff1-b431-121bbbaf7818">

**Comment by akatsukiro** [comment]
![图片](https://github.com/lsky-org/lsky-pro/assets/69096852/9d706a81-80da-448c-bf81-ceea65ff74e4)
选中时背景为蓝色，点击确认后背景是灰色。你的没有背景，也就是说没选中角色组进行绑定。点一下就好了。

**Comment by loohalh** [comment]
> ![图片](https://private-user-images.githubusercontent.com/69096852/301726528-9d706a81-80da-448c-bf81-ceea65ff74e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NDg4NzgsIm5iZiI6MTcwNjg0ODU3OCwicGF0aCI6Ii82OTA5Njg1Mi8zMDE3MjY1MjgtOWQ3MDZhODEtODBkYS00NDhjLWJmODEtY2VlYTY1ZmY3NGU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDA0MzYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmMDdhNmI4NDYxMTVkNjAzY2YzNmRhYTY5NzZiMjFjZGQwYjcyNDU5NGE0MTc3YzgwNjU1MDc3M2VhNjkzNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.q4Gzf7RUKWaRBHanU5j9_n3RPt8J2l6x4mNORuW42IQ)
> 选中时背景为蓝色，失去焦点后背景是灰色。你的没有背景，也就是说没选中角色组进行绑定。点一下就好了。

明白了 能显示了 谢谢大佬
