### ISSUE TITLE
反应个缩略图问题

### ISSUE THREAD

**Issue by setube** [lsky-org/lsky-pro#768]
比方说我上传之前就把图片压缩了,上传前是20kb上传之后缩略图会生成一个200kb左右的图片
![](https://i0.hdslb.com/bfs/article/37628111b2d2bcc1ad484af47caaf3c38941412.png)
![](https://i0.hdslb.com/bfs/article/bc732675a7f83d6a7532445caeb0544f8941412.png)

**Comment by akatsukiro** [comment]
https://github.com/lsky-org/lsky-pro/blob/911275c13b038c7a8b710de44664f23887eeb6f6/app/Services/ImageService.php#L571

我猜只要把这个60调小就行了。

**Comment by setube** [comment]
> app/Services/ImageService.php

我直接把缩略图全部换成的我自己上传的图片,然后把处理缩略图那给注释掉了

**Comment by comsami** [comment]
可以禁止特定副檔名關閉預覽嗎?
我上傳一個近50MB的GIF，每次開相冊都會卡在這個圖片讀取
導致其他圖片點選時毫無反應
