### ISSUE TITLE
建议添加在上传时选择上传的文件夹，这样可以规避整理图片麻烦的问题

### ISSUE THREAD

**Issue by kaygb** [lsky-org/lsky-pro#77]
我目前写文章时上传的图片都会在上传后统一新建一个文件夹进行整理，如果可以在上传之前建立文件夹，然后在上传时选择刚才新建文件夹就好了，这样的话使用起来更加的便捷，望采纳。感谢作者的幸苦开发，谢谢您。

**Comment by wisp-x** [comment]
目前设置中可以直接指定默认上传文件夹，设置后，每次上传的图片都会在该文件夹中。

**Comment by kaygb** [comment]
> 目前设置中可以直接指定默认上传文件夹，设置后，每次上传的图片都会在该文件夹中。

可能您理解错我的意思了，我的意思是在“我的图片"选项卡中的文件夹，而不是存储器的文件夹

**Comment by ldxw** [comment]
默认的上传文件夹是 `域名/年/月/日`
能自定义目录上传吗，就像 `域名/xxx/年/月/日` xxx就是自定义目录

**Comment by wisp-x** [comment]
可以，详见配置说明



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Mr.Lin <notifications@github.com&gt;
发送时间: 2020年3月3日 11:45
收件人: wisp-x/lsky-pro <lsky-pro@noreply.github.com&gt;
抄送: Wisp X <wisp-x@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[wisp-x/lsky-pro] 建议添加在上传时选择上传的文件夹，这样可以规避整理图片麻烦的问题 (#77)




默认的上传文件夹是 域名/年/月/日
 能自定义目录上传吗，就像 域名/xxx/年/月/日 xxx就是自定义目录

**Comment by wsczx** [comment]
能否云存储和本地存储路径分开设置？而不是目前设置的默认目录？比如：我自己的账号是设置的默认上传到七牛云根目录，但是其他用户设置的存储为本地时，也同样上传到服务器的根目录了，这样会造成图片全在服务器的根目录很混乱，谢谢！！！
