### ISSUE TITLE
上传的图片小概率失败，部分缩略图与图片实际不符

### ISSUE THREAD

**Issue by 99Mr-Z** [lsky-org/lsky-pro#798]
unraid系统，使用容器部署，并通过NPM进行反向代理。规则配置为：

location / {
    proxy_pass $forward_scheme://$server:$port;
    proxy_set_header Host $http_host;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Method $request_method;
    proxy_set_header X-Forwarded-Ssl on;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Original-URL $scheme://$http_host$request_uri;
    proxy_set_header X-Forwarded-Uri $request_uri;
}
修改变量ASSET_URL的值为反向代理的实际地址，
修改文件AppServiceProvider.php的http为https

1.无论通过本地或者反向代理的地址来进行图片上传，都有小概率上传失败，但通过查看设定的绝对路径来看，图片已经正常上传成功，暂时未能找到文件上传的错误日志路径，无法提供日志文件，若后续找到日志文件进行补充
2.上传成功的图片在我的图片中显示的缩略图与实际图片不一致
3.上传的图片可能会重复上传
例如023的缩略图显示成了025的缩略图

![image](https://github.com/lsky-org/lsky-pro/assets/117721493/2b01f214-2816-49da-8213-af6be969be76)
右下角部分为图片的实际编号
![image](https://github.com/lsky-org/lsky-pro/assets/117721493/6ff1366c-3f52-45c2-9e24-36bd7055fed0)
这个是正确的图片
![image](https://github.com/lsky-org/lsky-pro/assets/117721493/44ee1a3a-bacd-47cc-9f36-3e2a5e6874d6)

**Comment by 99Mr-Z** [comment]
另外如何修改用户的头像，并未找到具体的设定项能够修改头像

**Comment by 99Mr-Z** [comment]
上传失败，但实际已经上传成功，从文件来看数量也能对的上，但是是重复文件
![image](https://github.com/lsky-org/lsky-pro/assets/117721493/88a7c434-bb3c-4825-91c9-527febe0a45f)
![image](https://github.com/lsky-org/lsky-pro/assets/117721493/842d93d5-66b0-47a9-958a-77f140018089)

**Comment by WuMe-sicx** [comment]
可尝试开启debug f12查询报错日志

**Comment by Yurzi** [comment]
缩略图错配可能是多线程上传导致的，把这行里的 `$format` 改成 `$filename`大概就可以修好了

https://github.com/lsky-org/lsky-pro/blob/911275c13b038c7a8b710de44664f23887eeb6f6/app/Services/ImageService.php#L163

**Comment by 99Mr-Z** [comment]
> 缩略图错配可能是多线程上传导致的，把这行里的 `$format` 改成 `$filename`大概就可以修好了
> 
> https://github.com/lsky-org/lsky-pro/blob/911275c13b038c7a8b710de44664f23887eeb6f6/app/Services/ImageService.php#L163

好的，我尝试修改验证下，谢谢

**Comment by pipuwong** [comment]
Hi, 遇到同样的问题，只把 163 行的format改成filename，能修好吗。验证了吗

**Comment by 99Mr-Z** [comment]
> Hi, 遇到同样的问题，只把 163 行的format改成filename，能修好吗。验证了吗

暂时没有验证，只进行了修改，验证完成后回给你回复的

**Comment by 99Mr-Z** [comment]
> Hi, 遇到同样的问题，只把 163 行的format改成filename，能修好吗。验证了吗

目前使用了一段时间，没有再次出现过问题

**Comment by pipuwong** [comment]
感谢回复，我想请教下，我也是用Docker部署，请问如何修改哦？
