### ISSUE TITLE
全局域网环境下，使用AList的webdav存储，出现404

### ISSUE THREAD

**Issue by thissensen** [lsky-org/lsky-pro#831]
配置好AList的存储策略，可以正常上传图片，上传后在AList对应目录下显示出了上传的图片

![截图20241206120814](https://github.com/user-attachments/assets/ea49e8be-09be-4ce3-b4c3-dc3fcf9458c5)

![截图_20241206120744](https://github.com/user-attachments/assets/e6299c51-ccb7-4618-b9c4-a168b34dccad)

![截图20241206121115](https://github.com/user-attachments/assets/02500405-6c2d-4b0e-a476-7567539df7ab)

然后问题就来了，复制出的url显示404，只有缩略图是正常的

![截图20241206121338](https://github.com/user-attachments/assets/cb3da70d-041a-4819-a320-746111d854ab)

![截图20241206121428](https://github.com/user-attachments/assets/b5fa9483-a16d-4048-9e84-c880bf7b71e3)

图床Docker内部IP：172.18.0.4，通过端口映射可通过192.168.88.100访问，alist的ip地址在192.168.88.88

这种情况我应该如何解决

**Comment by wisp-x** [comment]
用 nginx 反向代理到内部 ip

**Comment by thissensen** [comment]
> 用 nginx 反向代理到内部 ip

我全都是内网IP也是要代理的吗，应该怎么填写啊，从未用过Nginx，请教一下，谢谢
图床Docker内部监听：172.18.0.4:8089
图床地址：192.168.88.100:40027
AList地址：192.168.88.88:5244
![截图20241206133002](https://github.com/user-attachments/assets/45902ea4-1f9d-4682-b999-02ed0d4b9c9e)

**Comment by wisp-x** [comment]
不好意思，没注意审题。

你这个应该需要使用 alist 的请求 ip 来访问图片，也就是 192.168.88.88，图床的储存策略中的访问域名填写 alist 的请求域名即可，但是我尚不清楚 alist 是否可以直接预览到图片。

**Comment by thissensen** [comment]
> 不好意思，没注意审题。
> 
> 你这个应该需要使用 alist 的请求 ip 来访问图片，也就是 192.168.88.88，图床的储存策略中的访问域名填写 alist 的请求域名即可，但是我尚不清楚 alist 是否可以直接预览到图片。

访问域名填写AList的链接的话就变成直接访问AList了，就会变成让你填写登录账号密码。由于AList只能对图片进行下载，做不到预览，所以我才想用Lsky进行管理。有TG或者Q群之类的吗，我可否进一步详细请教

**Comment by wisp-x** [comment]
@thissensen https://github.com/lsky-org/lsky-pro/issues/520#issuecomment-1661398028，浏览器直接访问是会下载的，不过 markdown 或 html 中引用显示是没问题的。

**Comment by wisp-x** [comment]
有点复杂了，但是有一个思路应该可以解决。

可以尝试一下在图床 `public` 目录创建符号链接，链接到 alist 的文件储存目录中。这样就可以通过图床的域名访问 alist 中的文件了，并且因为图床用的是 web 服务器 nginx，可以直接输出显示。

但是由于你是 docker 部署的，如果想要这样实现，必须通过 docker 具名 volume 或将 alist 和 图床的 `public` 挂载到宿主机，目的是两个程序共享一个文件系统。

**Comment by thissensen** [comment]
> 有点复杂了，但是有一个思路应该可以解决。
> 
> 可以尝试一下在图床 `public` 目录创建符号链接，链接到 alist 的文件储存目录中。这样就可以通过图床的域名访问 alist 中的文件了，并且因为图床用的是 web 服务器 nginx，可以直接输出显示。
> 
> 但是由于你是 docker 部署的，如果想要这样实现，必须通过 docker 具名 volume 或将 alist 和 图床的 `public` 挂载到宿主机，目的是两个程序共享一个文件系统。

这也是我现在想的，1、把alist的目录挂载到宿主机目录A。2、把目录A通过Docker映射给lsky。3、lsky设置本地存储，存储路径填写隐射的路径。只能这样了吧……
